### PR TITLE
Add `testthat` helper state

### PR DESCRIPTION
**Pull request by etiennebacher**
https://github.com/easystats/easystats/issues/388

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
There is one warning. Strange that the workflow isn't failing.

````r
Warning (test-standardize_models.R:285:1): brms
Global state has changed:
names(before[[4]])[93:98] vs names(after[[4]])[93:100]
  "PERFLOG_LOCATION_SETTING"
  "PIPX_BIN_DIR"
  "PIPX_HOME"
  "PKGCACHE_HTTP_VERSION"
+ "PKG_CPPFLAGS"
+ "PKG_LIBS"
  "POWERSHELL_DISTRIBUTION_CHANNEL"
  "PROCESSX_PSXCINVC0FQM_1697110500"
  "PWD"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
before[[4]][93:98] vs after[[4]][93:100]
  PERFLOG_LOCATION_SETTING"RUNNER_PERFLOG"
  PIPX_BIN_DIR"/opt/pipx_bin"
  PIPX_HOME"/opt/pipx"
  PKGCACHE_HTTP_VERSION"2"
+ PKG_CPPFLAGS"  -I\"/home/runner/work/_temp/Library/Rcpp/include/\"  -I\"/home/runner/work/_temp/Library/RcppEigen/include/\"  -I\"/home/runner/work/_temp/Library/RcppEigen/include/unsupported\"  -I\"/home/runner/work/_temp/Library/BH/include\" -I\"/home/runner/work/_temp/Library/StanHeaders/include/src/\"  -I\"/home/runner/work/_temp/Library/StanHeaders/include/\"  -I\"/home/runner/work/_temp/Library/RcppParallel/include/\"  -I\"/home/runner/work/_temp/Library/rstan/include\" -DEIGEN_NO_DEBUG  -DBOOST_DISABLE_ASSERTS  -DBOOST_PENDING_INTEGER_LOG2_HPP  -DSTAN_THREADS  -DUSE_STANC3 -DSTRICT_R_HEADERS  -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION  -DBOOST_NO_AUTO_PTR  -include '/home/runner/work/_temp/Library/StanHeaders/include/stan/math/prim/fun/Eigen.hpp'  -D_REENTRANT -DRCPP_PARALLEL_USE_TBB=1 "
+ PKG_LIBS" '/home/runner/work/_temp/Library/rstan/lib//libStanServices.a' -L'/home/runner/work/_temp/Library/StanHeaders/lib/' -lStanHeaders -L'/home/runner/work/_temp/Library/RcppParallel/lib/' -ltbb "
  POWERSHELL_DISTRIBUTION_CHANNEL"GitHub-Actions-ubuntu22"
  PROCESSX_PSXCINVC0FQM_1697110500"YES"
  PWD"/home/runner/work/datawizard/datawizard"
────────────────────────────────────────────────────────────────────────────────
```

**Comment by IndrajeetPatil** [comment]
https://github.com/easystats/datawizard/actions/runs/6495062798/job/17639250287?pr=465

**Comment by etiennebacher** [comment]
Actually, maybe this `check-tests-warnings` is broken? I removed all tests but one in `datawizard` and put a `warning()` call inside. Then I ran:
```r
options(crayon.enabled = TRUE, warn = 2L)
devtools::test()
```
and it showed a test warning but not a failure

**Comment by IndrajeetPatil** [comment]
Strange. This is what we used initially to detect test warnings

Will have a look. 

Can you please create an issue in our workflows repository?

**Comment by etiennebacher** [comment]
I see that all CI is passing now, @IndrajeetPatil can this be merged or are you experimenting with the warnings workflow?

**Review by IndrajeetPatil — APPROVED** [review]

**Comment by etiennebacher** [comment]
So there's a bunch of CI failures for various reasons (https://github.com/easystats/datawizard/issues/509, `pak` installation failures, `Matrix` issues, etc.) but none that are due to this PR so I merge this.

**Pull request merged**
