### PR TITLE
minor speed improvement

### PR DESCRIPTION
**Pull request by strengejacke**
``` r
library(datawizard)
microbenchmark::microbenchmark(
  text_concatenate(c("First", "Second", "Last")),
  times = 500
)
#> Unit: microseconds
#>                                            expr  min   lq    mean median uq
#>  text_concatenate(c("First", "Second", "Last")) 33.6 36.9 38.8976   37.3 38
#>    max neval
#>  367.2   500

microbenchmark::microbenchmark(
  text_concatenate(c("First", "Second", "Last"), last = " or ", enclose = "`"),
  times = 500
)
#> Unit: microseconds
#>                                                                               expr
#>  text_concatenate(c("First", "Second", "Last"), last = " or ",      enclose = "`")
#>   min    lq    mean median   uq   max neval
#>  38.2 42.15 45.5006  43.75 45.7 144.7   500
```

<sup>Created on 2023-03-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

``` r
library(datawizard)
microbenchmark::microbenchmark(
  text_concatenate(c("First", "Second", "Last")),
  times = 500
)
#> Unit: microseconds
#>                                            expr  min   lq   mean median    uq
#>  text_concatenate(c("First", "Second", "Last")) 11.2 12.2 17.752   12.9 21.65
#>    max neval
#>  322.7   500

microbenchmark::microbenchmark(
  text_concatenate(c("First", "Second", "Last"), last = " or ", enclose = "`"),
  times = 500
)
#> Unit: microseconds
#>                                                                               expr
#>  text_concatenate(c("First", "Second", "Last"), last = " or ",      enclose = "`")
#>   min   lq   mean median   uq max neval
#>  17.4 18.3 21.114     19 19.8  88   500
```

<sup>Created on 2023-03-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by etiennebacher** [comment]
Thanks but usually for benchmarks you want to look for gains at a larger scale because there are some overheads during the function call that make it hard to interpret the results at the microsecond.

Also, the package `bench` is preferred over `microbenchmark` (more precise and automatically checks that outputs are identical).

Here, if we increase the size of text vector a bit we can see that there's basically no difference:
``` r
### Compare existing text_concatenate to the one with changes in PR

text_concatenate <- function(text, sep = ", ", last = " and ", enclose = NULL) {
  text <- text[text != ""]
  if (length(text) && !is.null(enclose) && length(enclose) == 1 && nchar(enclose) > 0) {
    text <- paste0(enclose, text, enclose)
  }
  if (length(text) == 1) {
    s <- text
  } else {
    s <- paste0(utils::head(text, -1), collapse = sep)
    s <- paste0(c(s, utils::tail(text, 1)), collapse = last)
  }
  s
}

new_text_concatenate <- function(text, sep = ", ", last = " and ", enclose = NULL) {
  text <- text[text != ""]
  if (length(text) && !is.null(enclose) && length(enclose) == 1 && nchar(enclose) > 0) {
    text <- paste0(enclose, text, enclose)
  }
  if (length(text) == 1) {
    s <- text
  } else {
    s <- paste0(text[1:(length(text) - 1)], collapse = sep)
    s <- paste0(c(s, text[length(text)]), collapse = last)
  }
  s
}

test <- rep("abcde", 10000)

bench::mark(
  old = text_concatenate(test),
  new = new_text_concatenate(test),
  iterations = 1000
)
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 old          1.75ms   1.97ms      440.     543KB     3.10
#> 2 new          1.73ms   1.85ms      470.     391KB     3.32

bench::mark(
  old = text_concatenate(test, last = " or ", enclose = "`"),
  new = new_text_concatenate(test, last = " or ", enclose = "`"),
  iterations = 1000
)
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 old          3.98ms   5.78ms      175.     645KB     1.41
#> 2 new          3.96ms   4.54ms      202.     469KB     1.83


### Compare base and insight trimws

test2 <- rep("  Some text. ", 10000)

bench::mark(
  base = trimws(test2),
  insight = insight::trim_ws(test2),
  iterations = 1000
)
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 base         5.08ms   6.08ms      152.  156.34KB    0.305
#> 2 insight      6.15ms   6.54ms      137.    1.33MB    0.275
```

<sup>Created on 2023-03-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
For most "common" use cases (i.e. vectors of smaller length), it's slightly more efficient, and on large vectors they're on par.

plot2

Regarding memory allocation, `head()` and `tail()` produce more overhead.

plot

**Comment by strengejacke** [comment]
(code)

```r
install.packages("bench", dependencis = TRUE)

text_concatenate <- function(text, sep = ", ", last = " and ", enclose = NULL) {
  text <- text[text != ""]
  if (length(text) && !is.null(enclose) && length(enclose) == 1 && nchar(enclose) > 0) {
    text <- paste0(enclose, text, enclose)
  }
  if (length(text) == 1) {
    s <- text
  } else {
    s <- paste0(utils::head(text, -1), collapse = sep)
    s <- paste0(c(s, utils::tail(text, 1)), collapse = last)
  }
  s
}

new_text_concatenate <- function(text, sep = ", ", last = " and ", enclose = NULL) {
  text <- text[text != ""]
  if (length(text) && !is.null(enclose) && length(enclose) == 1 && nchar(enclose) > 0) {
    text <- paste0(enclose, text, enclose)
  }
  if (length(text) == 1) {
    s <- text
  } else {
    s <- paste0(text[1:(length(text) - 1)], collapse = sep)
    s <- paste0(c(s, text[length(text)]), collapse = last)
  }
  s
}

result <- NULL
for (i in 1:100) {
  test <- rep("abcde", 10 * i)

  out <- bench::mark(
    old = text_concatenate(test),
    new = new_text_concatenate(test),
    iterations = 1000
  )

  out$text_length <- 10 * i
  result <- rbind(result, out)
}

d <- as.data.frame(result[c("text_length", "median", "mem_alloc", "expression")])
d$median <- as.numeric(d$median)
d$mem_alloc <- as.numeric(d$mem_alloc)
d$expression <- as.character(d$expression)

library(ggplot2)
p1 <- ggplot(d, aes(x = text_length, y = median, colour = expression)) +
  geom_line() +
  labs(x = "Length of vector", y = "Median time", title = NULL) +
  stat_smooth()

p2 <- ggplot(d, aes(x = text_length, y = mem_alloc, colour = expression)) +
  geom_line() +
  labs(x = "Length of vector", y = "Memory allocation", title = NULL)
  # stat_smooth()

p1
p2
```

**Comment by etiennebacher** [comment]
Thanks for the detailed results, I reopen and will merge it then but I already submitted to CRAN this morning

**Comment by strengejacke** [comment]
It's not a really critical issue ;-)

**Pull request merged**
