### PR TITLE
Release 0.10.0

### LINKED ISSUE #489: CRAN submission?
WDYT, @etiennebacher ?

It's been a while since the last CRAN release, and we again have some new features added to the package. Not sure if you would like #488 included, but that's no that important, imho. But we could wait for that PR if you like.

### PR DESCRIPTION
**Pull request by etiennebacher**
Close #489 

Unable to run `revdepcheck` locally (and maybe on CI too) due to https://github.com/r-lib/revdepcheck/issues/376

### CODE REVIEW

**Comment by strengejacke** [comment]
You can run revdep checks using base R, that worked for me. I can post the script later

**Comment by strengejacke** [comment]
copy the source file into the specified directory and then run the script:

```r
tools::check_packages_in_dir(
  dir = "c:/Users/Daniel/Documents/GitHub/revdep_check/",
  check_args = c("--as-cran", ""),
  reverse = list(repos = getOption("repos")["CRAN"])
)
```

**Comment by etiennebacher** [comment]
> copy the source file into the specified directory and then run the script:

I don't think it's able to tell whether there are new errors, right? Currently I have some errors in `parameters` but that seems unrelated to `datawizard` update. Anyway, I launched some checks on win-devel and rhub and I'll submit later tonight or tomorrow

**Comment by strengejacke** [comment]
Not sure, it tells you whether any of the reverse dependency checks failed. I used this to check performance when I had problems with the revdep package

**Comment by strengejacke** [comment]
If not too late, we could wait for #493

**Comment by etiennebacher** [comment]
Yes I'll include #493 in this release

**Pull request merged**
