### PR TITLE
Preserve attr

### PR DESCRIPTION
**Pull request by strengejacke**
#136

### CODE REVIEW

**Comment by strengejacke** [comment]
@IndrajeetPatil can you check the snapshot tests? Why did these change? AFAIK, I have made no changes to that function affected, so I'm not sure if there are any new issues in other code places?

**Comment by IndrajeetPatil** [comment]
Looks like the print method has changed?

Instead of Min-Max, there is a Range column now. 

```r
 "Output"
  - "  Mean | SD | Min | Max | Skewness | Kurtosis |  n | n_Missing"
  + "  Mean | SD |    Range | Skewness | Kurtosis |  n | n_Missing"
  - "  ------------------------------------------------------------"
  + "  -----------------------------------------------------------"
  - "  NA   | NA |  VC |  OJ |        0 |     -2.1 | 60 |         0"
  + "       |    | [VC, OJ] |        0 |    -2.07 | 60 |         0"
```

**Comment by strengejacke** [comment]
But why?

**Comment by strengejacke** [comment]
I have a guess, maybe the print used datawizard-functions, let me see

**Comment by strengejacke** [comment]
``` r
library(datawizard)
describe_distribution(iris, include_factors = TRUE, quartiles = TRUE)
#> Variable     | Mean |   SD |  IQR |    Min |       Max |  Q1 |  Q3 | Skewness | Kurtosis |   n | n_Missing
#> ----------------------------------------------------------------------------------------------------------
#> Sepal.Length |  5.8 | 0.83 | 1.30 |    4.3 |       7.9 | 5.1 | 6.4 |     0.31 |    -0.55 | 150 |         0
#> Sepal.Width  |  3.1 | 0.44 | 0.52 |      2 |       4.4 | 2.8 | 3.3 |     0.32 |     0.23 | 150 |         0
#> Petal.Length |  3.8 | 1.77 | 3.52 |      1 |       6.9 | 1.6 | 5.1 |    -0.27 |    -1.40 | 150 |         0
#> Petal.Width  |  1.2 | 0.76 | 1.50 |    0.1 |       2.5 | 0.3 | 1.8 |    -0.10 |    -1.34 | 150 |         0
#> Species      |   NA |   NA |   NA | setosa | virginica |  NA |  NA |     0.00 |    -1.51 | 150 |         0

library(parameters)
describe_distribution(iris, include_factors = TRUE, quartiles = TRUE)
#> Variable     | Mean |   SD |  IQR |               Range |  Quartiles | Skewness | Kurtosis |   n | n_Missing
#> ------------------------------------------------------------------------------------------------------------
#> Sepal.Length | 5.84 | 0.83 | 1.30 |          [4.3, 7.9] | 5.10, 6.40 |     0.31 |    -0.55 | 150 |         0
#> Sepal.Width  | 3.06 | 0.44 | 0.52 |            [2, 4.4] | 2.80, 3.30 |     0.32 |     0.23 | 150 |         0
#> Petal.Length | 3.76 | 1.77 | 3.52 |            [1, 6.9] | 1.60, 5.10 |    -0.27 |    -1.40 | 150 |         0
#> Petal.Width  | 1.20 | 0.76 | 1.50 |          [0.1, 2.5] | 0.30, 1.80 |    -0.10 |    -1.34 | 150 |         0
#> Species      |      |      |      | [setosa, virginica] |            |     0.00 |    -1.51 | 150 |         0
```

<sup>Created on 2022-03-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
The `format()` method is in _parameters_, and the package is now loaded in tests. I.e. the print depends on whether parameters is loaded after datawizard or not.

**Comment by strengejacke** [comment]
Following methods should be moved to datawizard:

- format.parameters_distribution
- plot.parameters_distribution
- print_md.parameters_distribution
- display.parameters_distribution

**Comment by strengejacke** [comment]
maybe print_md and display make less sense, but `plot()` probably. But `plot()` should still work if only _parameters_ is loaded.

**Comment by strengejacke** [comment]
``` r
library(datawizard)
describe_distribution(iris, include_factors = TRUE, quartiles = TRUE)
#> Variable     | Mean |   SD |  IQR |               Range |  Quartiles | Skewness | Kurtosis |   n | n_Missing
#> ------------------------------------------------------------------------------------------------------------
#> Sepal.Length | 5.84 | 0.83 | 1.30 |          [4.3, 7.9] | 5.10, 6.40 |     0.31 |    -0.55 | 150 |         0
#> Sepal.Width  | 3.06 | 0.44 | 0.52 |            [2, 4.4] | 2.80, 3.30 |     0.32 |     0.23 | 150 |         0
#> Petal.Length | 3.76 | 1.77 | 3.52 |            [1, 6.9] | 1.60, 5.10 |    -0.27 |    -1.40 | 150 |         0
#> Petal.Width  | 1.20 | 0.76 | 1.50 |          [0.1, 2.5] | 0.30, 1.80 |    -0.10 |    -1.34 | 150 |         0
#> Species      |      |      |      | [setosa, virginica] |            |     0.00 |    -1.51 | 150 |         0

library(parameters)
#> Registered S3 method overwritten by 'parameters':
#>   method                         from      
#>   format.parameters_distribution datawizard
describe_distribution(iris, include_factors = TRUE, quartiles = TRUE)
#> Variable     | Mean |   SD |  IQR |               Range |  Quartiles | Skewness | Kurtosis |   n | n_Missing
#> ------------------------------------------------------------------------------------------------------------
#> Sepal.Length | 5.84 | 0.83 | 1.30 |          [4.3, 7.9] | 5.10, 6.40 |     0.31 |    -0.55 | 150 |         0
#> Sepal.Width  | 3.06 | 0.44 | 0.52 |            [2, 4.4] | 2.80, 3.30 |     0.32 |     0.23 | 150 |         0
#> Petal.Length | 3.76 | 1.77 | 3.52 |            [1, 6.9] | 1.60, 5.10 |    -0.27 |    -1.40 | 150 |         0
#> Petal.Width  | 1.20 | 0.76 | 1.50 |          [0.1, 2.5] | 0.30, 1.80 |    -0.10 |    -1.34 | 150 |         0
#> Species      |      |      |      | [setosa, virginica] |            |     0.00 |    -1.51 | 150 |         0
```

<sup>Created on 2022-03-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Pull request merged**
