### PR TITLE
Improve reshape longer

### PR DESCRIPTION
**Pull request by etiennebacher**
Related to #15:
* add `names_prefix`, `names_sep` and `names_pattern` (`names_pattern` is quite slower than `pivot_longer` implementation)
* add `values_drop_na`
* deprecate `colnames_to` in favor of  `names_to`

A few examples:
 ``` r
library(tidyr)
library(dplyr)
library(datawizard)


### Example 1
tidyr1 <- who |> 
  pivot_longer(
    cols = new_sp_m014:newrel_f65,
    names_to = c("diagnosis", "gender", "age"),
    names_pattern = "new_?(.*)_(.)(.*)",
    values_to = "count"
  )

datawiz1 <- who %>% 
  reshape_longer(
    select = 5:60,
    names_to = c("diagnosis", "gender", "age"),
    names_pattern = "new_?(.*)_(.)(.*)",
    values_to = "count"
  )

identical(datawiz1, tidyr1)
#> [1] TRUE


### Example 2
tidyr2 <- billboard %>% 
  pivot_longer(
    cols = starts_with("wk"), 
    names_to = "week", 
    names_prefix = "wk",
    values_to = "rank",
    values_drop_na = TRUE
  )

datawiz2 <- billboard %>% 
  reshape_longer(
    select = starts_with("wk"), 
    names_to = "week", 
    names_prefix = "wk",
    values_to = "rank",
    values_drop_na = TRUE
  )

identical(datawiz2, tidyr2)
#> [1] TRUE
```
<sup>Created on 2022-07-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Not working** (and no idea of how to implement this for now):
``` r
library(tidyr)
library(dplyr)
library(datawizard)


family <- tribble(
  ~family,  ~dob_child1,  ~dob_child2, ~gender_child1, ~gender_child2,
  1L, "1998-11-26", "2000-01-29",             1L,             2L,
  2L, "1996-06-22",           NA,             2L,             NA,
  3L, "2002-07-11", "2004-04-05",             2L,             2L,
  4L, "2004-10-10", "2009-08-27",             1L,             1L,
  5L, "2000-12-05", "2005-02-28",             2L,             1L,
)
family
#> # A tibble: 5 × 5
#>   family dob_child1 dob_child2 gender_child1 gender_child2
#>    <int> <chr>      <chr>              <int>         <int>
#> 1      1 1998-11-26 2000-01-29             1             2
#> 2      2 1996-06-22 <NA>                   2            NA
#> 3      3 2002-07-11 2004-04-05             2             2
#> 4      4 2004-10-10 2009-08-27             1             1
#> 5      5 2000-12-05 2005-02-28             2             1

tidyr <- family %>% 
  pivot_longer(
    !family, 
    names_to = c(".value", "child"), 
    names_sep = "_", 
    values_drop_na = TRUE
  )

datawiz <- family %>% 
  reshape_longer(
    select = -family, 
    names_to = c(".value", "child"), 
    names_sep = "_", 
    values_drop_na = TRUE
  )

identical(datawiz, tidyr)
#> [1] FALSE
```

<sup>Created on 2022-07-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### CODE REVIEW

**Comment by etiennebacher** [comment]
This PR is now ready for review. Three points to discuss:
* apparently `cols` is deprecated in favor of `select`. @strengejacke I guess you did that for consistency of select helpers across datawizard, but it decreases compatibility with pivot_longer, which uses `cols`. What should be done here?
* for consistency with tidyr, I change the default of `names_to` from "Name" to "name", and the default of `values_to` from "Value" to "value". Are you ok with that or is it a breaking change?
* I have no idea how to deal with tidyr's special name ".value" like in the following example:
``` r
library(tidyr)

pnl <- tibble(
  x = 1:4,
  a = c(1, 1,0, 0),
  b = c(0, 1, 1, 1),
  y1 = rnorm(4),
  y2 = rnorm(4),
  z1 = rep(3, 4),
  z2 = rep(-2, 4),
)

pnl %>% 
  pivot_longer(
    !c(x, a, b), 
    names_to = c(".value", "time"), 
    names_pattern = "(.)(.)"
  )
#> # A tibble: 8 × 6
#>       x     a     b time          y     z
#>   <int> <dbl> <dbl> <chr>     <dbl> <dbl>
#> 1     1     1     0 1     -0.203        3
#> 2     1     1     0 2      0.000715    -2
#> 3     2     1     1 1      0.771        3
#> 4     2     1     1 2      0.497       -2
#> 5     3     0     1 1     -0.0517       3
#> 6     3     0     1 2      0.223       -2
#> 7     4     0     1 1      0.705        3
#> 8     4     0     1 2     -0.503       -2
```
<sup>Created on 2022-07-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by IndrajeetPatil** [comment]
Thanks, @etiennebacher. Can you please resolve the merge conflicts before we take a look?

**Comment by bwiernik** [comment]
And show the current reprex's?

**Comment by etiennebacher** [comment]
``` r
library(tidyr)
library(dplyr)
library(datawizard)

##### Example 1

tidyr1 <- relig_income %>% 
  pivot_longer(!religion, names_to = "income", values_to = "count")

datawiz1 <- relig_income %>% 
  reshape_longer(select = -religion, names_to = "income", values_to = "count")

identical(datawiz1, tidyr1)
#> [1] TRUE


##### Example 2

tidyr2 <- billboard %>% 
  pivot_longer(
    cols = starts_with("wk"), 
    names_to = "week", 
    values_to = "rank"
  )

datawiz2 <- billboard %>% 
  reshape_longer(
    select = starts_with("wk"), 
    names_to = "week", 
    values_to = "rank"
  )

identical(datawiz2, tidyr2)
#> [1] TRUE


##### Example 3

tidyr3 <- billboard %>% 
  pivot_longer(
    cols = starts_with("wk"), 
    names_to = "week", 
    values_to = "rank",
    values_drop_na = TRUE
  )

datawiz3 <- billboard %>% 
  reshape_longer(
    select = starts_with("wk"), 
    names_to = "week", 
    values_to = "rank",
    values_drop_na = TRUE
  )

identical(datawiz3, tidyr3)
#> [1] TRUE


##### Example 4

tidyr4 <- billboard %>% 
  pivot_longer(
    cols = starts_with("wk"), 
    names_to = "week", 
    names_prefix = "wk",
    values_to = "rank",
    values_drop_na = TRUE
  )

datawiz4 <- billboard %>% 
  reshape_longer(
    select = starts_with("wk"), 
    names_to = "week", 
    names_prefix = "wk",
    values_to = "rank",
    values_drop_na = TRUE
  )

identical(datawiz4, tidyr4)
#> [1] TRUE


##### Example 5

tidyr5 <- who |> 
  pivot_longer(
    cols = 5:60,
    names_to = c("diagnosis", "gender", "age"),
    names_sep = "_",
    values_to = "count"
  )
#> Warning: Expected 3 pieces. Missing pieces filled with `NA` in 14 rows [43, 44,
#> 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56].

datawiz5 <- who %>% 
  reshape_longer(
    select = 5:60,
    names_to = c("diagnosis", "gender", "age"),
    names_sep = "_",
    values_to = "count"
  )

identical(datawiz5, tidyr5)
#> [1] TRUE


##### Example 6

tidyr6 <- who |> 
  pivot_longer(
    cols = new_sp_m014:newrel_f65,
    names_to = c("diagnosis", "gender", "age"),
    names_pattern = "new_?(.*)_(.)(.*)",
    values_to = "count"
  )

datawiz6 <- who %>% 
  reshape_longer(
    select = 5:60,
    names_to = c("diagnosis", "gender", "age"),
    names_pattern = "new_?(.*)_(.)(.*)",
    values_to = "count"
  )

identical(datawiz6, tidyr6)
#> [1] TRUE
```

<sup>Created on 2022-07-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by etiennebacher** [comment]
Not sure what to do here, I think we should favor either `select` or `cols` and deprecate the other one (as is currently the case) and remove it later to avoid cluttering the docs with unnecessary args. I don't have a clear-cut preference, both have pros and cons.

I'll wait for some inputs of other members on both points.

**Comment by IndrajeetPatil** [comment]
@etiennebacher Can you please resolve the merge conflicts here?

**Comment by etiennebacher** [comment]
@IndrajeetPatil done

**Comment by bwiernik** [comment]
> Not sure what to do here, I think we should favor either select or cols and deprecate the other one (as is currently the case) and remove it later to avoid cluttering the docs with unnecessary args. I don't have a clear-cut preference, both have pros and cons.

Hmm, the `cols` argument feels a little different in `reshape_longer()` than in most of the other functions, but I guess it's close enough. I guess let's go with `select`.

I like the feature that many `tidyr::pivot_*()` calls can be used without modifications in `reshape_longer()`, so I'm inclined to make `cols` possible. Perhaps we can absorb it into `...` and replace `select` with it if `select` not otherwise specified and error if both are provided? We can document that in the Details of the docs rather than in the arguments list?


> In general, we have the convention to use upper case column names. Not sure if this is a big deal here, I'm open for either way (i.e. either use lower case values, or upper case and not being consistent with tidyr).

I think the `{datawizard}` functions are a bit different that most of the *easystats* functions. I usually advocate for all lowercase variable names in R objects and data frame columns. So I think `"name", "`value`", etc. would be good defaults for `reshape_longer()`. Thoughts @mattansb @DominiqueMakowski @IndrajeetPatil ?

**Comment by mattansb** [comment]
> I like the feature that many tidyr::pivot_*() calls can be used without modifications in reshape_longer(), so I'm inclined to make cols possible. Perhaps we can absorb it into ... and replace select with it if select not otherwise specified and error if both are provided? We can document that in the Details of the docs rather than in the arguments list?

Yes, I like this too.

**Comment by etiennebacher** [comment]
> Perhaps we can absorb it into ... and replace select with it if select not otherwise specified and error if both are provided?

`select = "all"` by default, so this would require the user to add `select = NULL` if they want to avoid the error. I think it makes more sense to simply use `cols` if it is specified. That way, the user can just copy the code from `tidyr::pivot_longer()`, change the function name and it works:
``` r
library(tidyr)
library(datawizard)

### Example 1

tidyr <- billboard %>%
  pivot_longer(
    cols = starts_with("wk"),
    names_to = "week",
    names_prefix = "wk",
    values_to = "rank",
    values_drop_na = TRUE
  )

datawiz_cols <- billboard %>%
  reshape_longer(
    cols = starts_with("wk"),
    names_to = "week",
    names_prefix = "wk",
    values_to = "rank",
    values_drop_na = TRUE
  )

datawiz_select <- billboard %>%
  reshape_longer(
    select = starts_with("wk"),
    names_to = "week",
    names_prefix = "wk",
    values_to = "rank",
    values_drop_na = TRUE
  )

identical(tidyr, datawiz_select)
#> [1] TRUE
identical(tidyr, datawiz_cols)
#> [1] TRUE


### Example 2

tidyr <- who %>%
  pivot_longer(
    cols = 5:60,
    names_to = c("diagnosis", "gender", "age"),
    names_sep = "_",
    values_to = "count"
  )
#> Warning: Expected 3 pieces. Missing pieces filled with `NA` in 14 rows [43, 44,
#> 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56].

datawiz_cols <- who %>%
  reshape_longer(
    cols = 5:60,
    names_to = c("diagnosis", "gender", "age"),
    names_sep = "_",
    values_to = "count"
  )

datawiz_select <- who %>%
  reshape_longer(
    select = 5:60,
    names_to = c("diagnosis", "gender", "age"),
    names_sep = "_",
    values_to = "count"
  )

identical(tidyr, datawiz_select)
#> [1] TRUE
identical(tidyr, datawiz_cols)
#> [1] TRUE
```

<sup>Created on 2022-07-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Review by IndrajeetPatil — APPROVED** [review]

**Comment by etiennebacher** [comment]
@strengejacke @bwiernik are you ok to merge this?

**Comment by bwiernik** [comment]
> I think it makes more sense to simply use cols if it is specified. 

I agree with this. Okay to merge if that's what's implemented

**Comment by IndrajeetPatil** [comment]
> Okay to merge if that's what's implemented

Yepp, that's what's implemented now.

**Pull request merged**
