### PR TITLE
Add N% to N column #327

### LINKED ISSUE #327: FR: Display percentages instead of counts in `data_codebook()` output
As requested [here](https://twitter.com/JulienMouchnino/status/1600117104585629696?s=20&t=dCOsbVx8mCI_slInQgyL8A).

### PR DESCRIPTION
**Pull request by strengejacke**
Fix #327 

``` r
library(datawizard)
library(haven)
x <- labelled(
  x = c(1:3, tagged_na("a", "c", "z"),
        4:1, tagged_na("a", "a", "c"),
        1:3, tagged_na("z", "c", "c"),
        1:4, tagged_na("a", "c", "z")),
  labels = c("Agreement" = 1, "Disagreement" = 4,
              "First" = tagged_na("c"), "Refused" = tagged_na("a"),
              "Not home" = tagged_na("z"))
)
data_codebook(data.frame(x))
#> data.frame(x) (26 rows and 1 variables, 1 shown)
#> 
#> ID | Name | Type    |   Missings | Values | Value Labels |         N
#> ---+------+---------+------------+--------+--------------+----------
#> 1  | x    | numeric | 12 (46.2%) |      1 | Agreement    | 4 (15.4%)
#>    |      |         |            |      2 | 2            | 4 (15.4%)
#>    |      |         |            |      3 | 3            | 4 (15.4%)
#>    |      |         |            |      4 | Disagreement | 2 ( 7.7%)
#>    |      |         |            |  NA(a) | Refused      | 4 (15.4%)
#>    |      |         |            |  NA(c) | First        | 5 (19.2%)
#>    |      |         |            |  NA(z) | Not home     | 3 (11.5%)
#> --------------------------------------------------------------------


data(efc)
data_codebook(efc, variable_label_width = 30, value_label_width = 15)
#> efc (100 rows and 5 variables, 5 shown)
#> 
#> ID | Name     | Label                        | Type        |   Missings |   Values | Value Labels     |          N
#> ---+----------+------------------------------+-------------+------------+----------+------------------+-----------
#> 1  | c12hour  | average number of hours of   | numeric     |   2 (2.0%) | [5, 168] |                  |         98
#>    |          | care per week                |             |            |          |                  |           
#> ---+----------+------------------------------+-------------+------------+----------+------------------+-----------
#> 2  | e16sex   | elder's gender               | numeric     |   0 (0.0%) |        1 | male             | 46 (46.0%)
#>    |          |                              |             |            |        2 | female           | 54 (54.0%)
#> ---+----------+------------------------------+-------------+------------+----------+------------------+-----------
#> 3  | e42dep   | elder's dependency           | categorical |   3 (3.0%) |        1 | independent      |  2 ( 2.1%)
#>    |          |                              |             |            |        2 | slightly...      |  4 ( 4.1%)
#>    |          |                              |             |            |        3 | moderately...    | 28 (28.9%)
#>    |          |                              |             |            |        4 | severely...      | 63 (64.9%)
#> ---+----------+------------------------------+-------------+------------+----------+------------------+-----------
#> 4  | c172code | carer's level of education   | numeric     | 10 (10.0%) |        1 | low level of...  |  8 ( 8.9%)
#>    |          |                              |             |            |        2 | intermediate...  | 66 (73.3%)
#>    |          |                              |             |            |        3 | high level of... | 16 (17.8%)
#> ---+----------+------------------------------+-------------+------------+----------+------------------+-----------
#> 5  | neg_c_7  | Negative impact with 7 items | numeric     |   3 (3.0%) |  [7, 28] |                  |         97
#> ------------------------------------------------------------------------------------------------------------------
```

<sup>Created on 2022-12-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by strengejacke** [comment]
@IndrajeetPatil Could you please update the `test-data_codebook` file and use snapshot tests instead?

**Comment by strengejacke** [comment]
wait, need to fix some issues first.

**Comment by strengejacke** [comment]
ok, ready for review/merge.

**Review by etiennebacher — APPROVED** [review]

**Comment by etiennebacher** [comment]
Looks great, thank you!

**Pull request merged**
