### PR TITLE
data_read

### PR DESCRIPTION
**Pull request by strengejacke**
generic function to import data of different file types.

### CODE REVIEW

**Comment by bwiernik** [comment]
I'm not sure that we need this. The {rio} package already exists and is also designed to be extremely lightweight, so I don't see the value add here

**Comment by strengejacke** [comment]
Yeah, true. The value added here is more a personal use case, `data_read()` converts into factors (but only those variables that _seem_ to be a factor), and drops unused factor levels automatically. `rio::factorize()`, however, converts values w/o labels for partially labelled vectors into `NA`. But sometimes you have labelled data, like a score from 1 to 10, where only 1 and 10 have value labels. `data_read()` would treat this as numeric, `rio::factorize()` would return a factor with 1 and 10, and all other values being `NA`.

**Comment by DominiqueMakowski** [comment]
Even if added value is low, it doesnt bother me to keep it if the specificities and potential use cases are stated

**Comment by bwiernik** [comment]
I would set the tests to run not on CRAN, then give a URL to the data file in path

**Comment by strengejacke** [comment]
We now have four more packages in the suggested-field... I agree that the **rio** package has lots of features, so `data_read()` doesn't add _much_... However, this is an example from a typical workflow for "new" R users and/or those who often deal with SPSS/Stata data files.

By default, `rio::import()` converts columns into numerics, and `factorize()` converts _all_ to factors. However, this is not always desired, and values of numeric variables, or partially labelled variables, are converted into `NA`. See following three examples, first `data_read()`, and then `rio::import()` default and after `factorize()`. Note that `data_read()` drops unused levels/labels, and tries to "guess" factors and only convert those into factors, preserving others as numeric/character.

``` r
d <- datawizard::data_read("C:/Users/DL/Documents/SynologyDrive/UKE_DL/Publikationen (Analysen)/2021 Deas Covid/Daten/SUF_DEAS2020_1-0_en_SPSS.sav")
#> Reading data...
#> Preparing data... Almost there!
sjmisc::frq(d$jp20)
#> Number of children (x) <numeric> 
#> # total N=4823 valid N=4574 mean=1.94 sd=1.11
#> 
#> Value | Label |    N | Raw % | Valid % | Cum. %
#> -----------------------------------------------
#>     0 |     0 |  371 |  7.69 |    8.11 |   8.11
#>     1 |     1 | 1101 | 22.83 |   24.07 |  32.18
#>     2 |     2 | 2046 | 42.42 |   44.73 |  76.91
#>     3 |     3 |  723 | 14.99 |   15.81 |  92.72
#>     4 |     4 |  227 |  4.71 |    4.96 |  97.68
#>     5 |     5 |   65 |  1.35 |    1.42 |  99.10
#>     6 |     6 |   25 |  0.52 |    0.55 |  99.65
#>     7 |     7 |    9 |  0.19 |    0.20 |  99.85
#>     8 |    8+ |    7 |  0.15 |    0.15 | 100.00
#>  <NA> |  <NA> |  249 |  5.16 |    <NA> |   <NA>

d <- rio::import("C:/Users/DL/Documents/SynologyDrive/UKE_DL/Publikationen (Analysen)/2021 Deas Covid/Daten/SUF_DEAS2020_1-0_en_SPSS.sav")
sjmisc::frq(d$jp20)
#> Number of children (x) <numeric> 
#> # total N=4823 valid N=4574 mean=1.94 sd=1.11
#> 
#> Value |                Label |    N | Raw % | Valid % | Cum. %
#> --------------------------------------------------------------
#>    -7 |              deleted |    0 |  0.00 |    0.00 |   0.00
#>    -6 |            no answer |    0 |  0.00 |    0.00 |   0.00
#>    -3 | filtered (not asked) |    0 |  0.00 |    0.00 |   0.00
#>    -2 |           don't know |    0 |  0.00 |    0.00 |   0.00
#>    -1 |             declined |    0 |  0.00 |    0.00 |   0.00
#>     0 |                    0 |  371 |  7.69 |    8.11 |   8.11
#>     1 |                    1 | 1101 | 22.83 |   24.07 |  32.18
#>     2 |                    2 | 2046 | 42.42 |   44.73 |  76.91
#>     3 |                    3 |  723 | 14.99 |   15.81 |  92.72
#>     4 |                    4 |  227 |  4.71 |    4.96 |  97.68
#>     5 |                    5 |   65 |  1.35 |    1.42 |  99.10
#>     6 |                    6 |   25 |  0.52 |    0.55 |  99.65
#>     7 |                    7 |    9 |  0.19 |    0.20 |  99.85
#>     8 |                   8+ |    7 |  0.15 |    0.15 | 100.00
#>  <NA> |                 <NA> |  249 |  5.16 |    <NA> |   <NA>
d <- rio::factorize(d)
sjmisc::frq(d$jp20)
#> Number of children (x) <categorical> 
#> # total N=4823 valid N=7 mean=6.00 sd=0.00
#> 
#> Value                |    N | Raw % | Valid % | Cum. %
#> ------------------------------------------------------
#> deleted              |    0 |  0.00 |       0 |      0
#> no answer            |    0 |  0.00 |       0 |      0
#> filtered (not asked) |    0 |  0.00 |       0 |      0
#> don't know           |    0 |  0.00 |       0 |      0
#> declined             |    0 |  0.00 |       0 |      0
#> 8+                   |    7 |  0.15 |     100 |    100
#> <NA>                 | 4816 | 99.85 |    <NA> |   <NA>
```

<sup>Created on 2022-04-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
An example for categorical:

``` r
d <- datawizard::data_read("C:/Users/DL/Documents/SynologyDrive/UKE_DL/Publikationen (Analysen)/2021 Deas Covid/Daten/SUF_DEAS2020_1-0_en_SPSS.sav")
#> Reading data...
#> Preparing data... Almost there!
sjmisc::frq(d$geschlecht_20)
#> Sex (x) <categorical> 
#> # total N=4823 valid N=4823 mean=1.51 sd=0.50
#> 
#> Value  |    N | Raw % | Valid % | Cum. %
#> ----------------------------------------
#> Male   | 2366 | 49.06 |   49.06 |  49.06
#> Female | 2457 | 50.94 |   50.94 | 100.00
#> <NA>   |    0 |  0.00 |    <NA> |   <NA>
levels(d$geschlecht_20)
#> [1] "Male"   "Female"

d <- rio::import("C:/Users/DL/Documents/SynologyDrive/UKE_DL/Publikationen (Analysen)/2021 Deas Covid/Daten/SUF_DEAS2020_1-0_en_SPSS.sav")
sjmisc::frq(d$geschlecht_20)
#> Sex (x) <numeric> 
#> # total N=4823 valid N=4823 mean=1.51 sd=0.50
#> 
#> Value |                Label |    N | Raw % | Valid % | Cum. %
#> --------------------------------------------------------------
#>    -7 |              deleted |    0 |  0.00 |    0.00 |   0.00
#>    -6 |            no answer |    0 |  0.00 |    0.00 |   0.00
#>    -3 | filtered (not asked) |    0 |  0.00 |    0.00 |   0.00
#>    -2 |           don't know |    0 |  0.00 |    0.00 |   0.00
#>    -1 |             declined |    0 |  0.00 |    0.00 |   0.00
#>     1 |                 Male | 2366 | 49.06 |   49.06 |  49.06
#>     2 |               Female | 2457 | 50.94 |   50.94 | 100.00
#>  <NA> |                 <NA> |    0 |  0.00 |    <NA> |   <NA>
d <- rio::factorize(d)
sjmisc::frq(d$geschlecht_20)
#> Sex (x) <categorical> 
#> # total N=4823 valid N=4823 mean=6.51 sd=0.50
#> 
#> Value                |    N | Raw % | Valid % | Cum. %
#> ------------------------------------------------------
#> deleted              |    0 |  0.00 |    0.00 |   0.00
#> no answer            |    0 |  0.00 |    0.00 |   0.00
#> filtered (not asked) |    0 |  0.00 |    0.00 |   0.00
#> don't know           |    0 |  0.00 |    0.00 |   0.00
#> declined             |    0 |  0.00 |    0.00 |   0.00
#> Male                 | 2366 | 49.06 |   49.06 |  49.06
#> Female               | 2457 | 50.94 |   50.94 | 100.00
#> <NA>                 |    0 |  0.00 |    <NA> |   <NA>
levels(d$geschlecht_20)
#> [1] "deleted"              "no answer"            "filtered (not asked)"
#> [4] "don't know"           "declined"             "Male"                
#> [7] "Female"
```

<sup>Created on 2022-04-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Pull request merged**
