### PR TITLE
Make `length(unique(x)) == 1` faster

### PR DESCRIPTION
**Pull request by etiennebacher**
Instead of getting all unique values and counting them, check whether each value in a vector is equal to the first one:

``` r
# Should be TRUE
test <- rep(1, 1e7)

bench::mark(
  length(unique(test)) == 1,
  all(test == test[1]),
  iterations = 10
)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 2 × 6
#>   expression                     min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 length(unique(test)) == 1  126.5ms  137.3ms      7.17   166.1MB     7.17
#> 2 all(test == test[1])        33.7ms   34.5ms     26.1     38.1MB     5.21

# Should be FALSE
test2 <- rep(c(1, 2), 1e7)

bench::mark(
  length(unique(test2)) == 1,
  all(test2 == test2[1]),
  iterations = 10
)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 2 × 6
#>   expression                      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                 <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 length(unique(test2)) == 1    244ms  279.7ms      3.61   332.3MB     3.61
#> 2 all(test2 == test2[1])       51.1ms   55.6ms     15.9     76.3MB     3.18
```

<sup>Created on 2022-11-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by strengejacke** [comment]
Does not work correctly in the case of an empty vector.

**Comment by strengejacke** [comment]
``` r
test <- c()
length(unique(test)) == 1
#> [1] FALSE
all(test == test[1])
#> [1] TRUE
```

<sup>Created on 2022-11-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
Maybe:

``` r
.has_one_value <- function(x) {
  !is.null(x) && isTRUE(all(x == x[1]))
}

.has_one_value2 <- function(x) {
  !is.null(x) && length(x) && isTRUE(all(x == x[1]))
}

x <- rep(1, 1e5)
bench::mark(
  length(unique(x)) == 1,
  .has_one_value(x),
  .has_one_value2(x),
  iterations = 100,

)
#> # A tibble: 3 × 6
#>   expression                  min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>             <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 length(unique(x)) == 1   1.37ms    1.4ms      711.    1.38MB     14.5
#> 2 .has_one_value(x)       464.5µs  469.6µs     2006.  390.67KB      0  
#> 3 .has_one_value2(x)      360.1µs  471.9µs     1984.  390.67KB     20.0

x <- c()
bench::mark(
  length(unique(x)) == 1,
  .has_one_value(x),
  .has_one_value2(x),
  iterations = 100,
)
#> # A tibble: 3 × 6
#>   expression                  min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>             <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 length(unique(x)) == 1      5µs    5.2µs   186532.        0B        0
#> 2 .has_one_value(x)         600ns    700ns  1408451.        0B        0
#> 3 .has_one_value2(x)        600ns    700ns  1366120.        0B        0
```

<sup>Created on 2022-11-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
Ok, just saw that `is.null()` takes care of this, so `.has_one_value()` also works for empty vectors.

**Comment by etiennebacher** [comment]
So is it ok to merge?

**Review by strengejacke — APPROVED** [review]

**Comment by strengejacke** [comment]
Yes

**Comment by mattansb** [comment]
Should this be a function in insight, with n_unique?

**Comment by etiennebacher** [comment]
Yes it could be exported by insight, @strengejacke what do you think?

**Comment by strengejacke** [comment]
Yes, good idea. _insight_ needs to be updated the next days, due to changes in _glmmTMB_, so we could have that function quite timely in the CRAN version.

One question: What does the comment "only work for numeric vectors" mean? The function seems to work for factors as well.

**Comment by etiennebacher** [comment]
Ah it's a typo, I used `mean()` in one of my attempts earlier so it worked only for numeric, but the comment is outdated now. 

I can make a PR in insight for this

**Comment by IndrajeetPatil** [comment]
@etiennebacher This needs to be updated to use the latest devel-insight, right?

**Comment by etiennebacher** [comment]
Yes

**Comment by etiennebacher** [comment]
Or should I just wait for the next version of insight to be on CRAN? There's no rush to implement this anyway

**Comment by strengejacke** [comment]
_insight_ update is on CRAN!

**Comment by IndrajeetPatil** [comment]
Thanks, @etiennebacher!

**Pull request merged**
