### PR TITLE
draft data_peek

### PR DESCRIPTION
**Pull request by strengejacke**
Comparanle to "glimpse()"

### CODE REVIEW

**Comment by strengejacke** [comment]
``` r
library(datawizard)
data(efc)
data_peek(efc)
#> Variable | Type        | Values                                        
#> -----------------------------------------------------------------------
#> c12hour  | numeric     | 16, 148, 70, NA, 168, 16, 161, 110, 28, ...   
#> e16sex   | numeric     | 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, ... 
#> e42dep   | categorical | 3, 3, 3, NA, 4, 4, 4, 4, 4, 4, 4, 3, 4, 3, ...
#> c172code | numeric     | 2, 2, 1, 2, 2, 2, 2, 2, NA, 2, 2, 2, 3, 1, ...
#> neg_c_7  | numeric     | 12, 20, 11, 10, 12, 19, 15, 11, 15, 10, ...
data_peek(to_factor(efc, select = c("e16sex", "c172code")))
#> Variable | Type        | Values                                        
#> -----------------------------------------------------------------------
#> c12hour  | numeric     | 16, 148, 70, NA, 168, 16, 161, 110, 28, ...   
#> e16sex   | categorical | female, female, female, female, female, ...   
#> e42dep   | categorical | 3, 3, 3, NA, 4, 4, 4, 4, 4, 4, 4, 3, 4, 3, ...
#> c172code | categorical | intermediate level of education, ...          
#> neg_c_7  | numeric     | 12, 20, 11, 10, 12, 19, 15, 11, 15, 10, ...
data_peek(iris)
#> Variable     | Type        | Values                                   
#> ----------------------------------------------------------------------
#> Sepal.Length | numeric     | 5.1, 4.9, 4.7, 4.6, 5, 5.4, 4.6, 5, ...  
#> Sepal.Width  | numeric     | 3.5, 3, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, ...
#> Petal.Length | numeric     | 1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, ...   
#> Petal.Width  | numeric     | 0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, ...   
#> Species      | categorical | setosa, setosa, setosa, setosa, ...
data_peek(iris, select = "^Sepal", regex = TRUE)
#> Variable     | Type    | Values                                        
#> -----------------------------------------------------------------------
#> Sepal.Length | numeric | 5.1, 4.9, 4.7, 4.6, 5, 5.4, 4.6, 5, 4.4, ...  
#> Sepal.Width  | numeric | 3.5, 3, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, ...
```

<sup>Created on 2022-09-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
``` r
library(datawizard)

data_peek(iris)
#> Variable     | Type        | Values                                   
#> ----------------------------------------------------------------------
#> Sepal.Length | numeric     | 5.1, 4.9, 4.7, 4.6, 5, 5.4, 4.6, 5, ...  
#> Sepal.Width  | numeric     | 3.5, 3, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, ...
#> Petal.Length | numeric     | 1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, ...   
#> Petal.Width  | numeric     | 0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, ...   
#> Species      | categorical | setosa, setosa, setosa, setosa, ...

data_peek(iris, n = 3)
#> Variable     | Type    | Values                                   
#> ------------------------------------------------------------------
#> Sepal.Length | numeric | 5.1, 4.9, 4.7, 4.6, 5, 5.4, 4.6, 5, ...  
#> Sepal.Width  | numeric | 3.5, 3, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, ...
#> Petal.Length | numeric | 1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, ...

data_peek(iris, width = 130)
#> Variable     | Type        | Values                                                                                              
#> ---------------------------------------------------------------------------------------------------------------------------------
#> Sepal.Length | numeric     | 5.1, 4.9, 4.7, 4.6, 5, 5.4, 4.6, 5, 4.4, 4.9, 5.4, 4.8, 4.8, 4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, ... 
#> Sepal.Width  | numeric     | 3.5, 3, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3, 3, 4, 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, ...
#> Petal.Length | numeric     | 1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4, 1.1, 1.2, 1.5, 1.3, 1.4, 1.7, ...  
#> Petal.Width  | numeric     | 0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1, 0.1, 0.2, 0.4, 0.4, 0.3, 0.3, ...  
#> Species      | categorical | setosa, setosa, setosa, setosa, setosa, setosa, setosa, setosa, setosa, setosa, setosa, setosa, ...
```

<sup>Created on 2022-09-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
@IndrajeetPatil Could you add snapshot tests? For following three examples:

```r
data_peek(iris)

data_peek(iris, n = 3)

data_peek(iris, width = 130)
```

**Comment by strengejacke** [comment]
``` r
library(datawizard)
data_peek(iris, width = 90) |> print_md()
```

| Variable     | Type        | Values                                                    |
|:-------------|:------------|:----------------------------------------------------------|
| Sepal.Length | numeric     | 5.1, 4.9, 4.7, 4.6, 5, 5.4, 4.6, 5, 4.4, 4.9, 5.4, 4.8, … |
| Sepal.Width  | numeric     | 3.5, 3, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, …    |
| Petal.Length | numeric     | 1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, …  |
| Petal.Width  | numeric     | 0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, …  |
| Species      | categorical | setosa, setosa, setosa, setosa, setosa, setosa, setosa, … |

Data frame with 150 rows and 5 columns

<sup>Created on 2022-09-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by bwiernik** [comment]
Benefit over `str()`?

**Comment by strengejacke** [comment]
Less cluttered output. In particular if data frames or columns have many attributes

**Comment by strengejacke** [comment]
And we have print methods for md and html 🙂

**Comment by strengejacke** [comment]
``` r
library(datawizard)
data_peek(iris)
#> Data frame with 150 rows and 5 columns
#> 
#> Variable     | Type        | Values                                   
#> ----------------------------------------------------------------------
#> Sepal.Length | numeric     | 5.1, 4.9, 4.7, 4.6, 5, 5.4, 4.6, 5, ...  
#> Sepal.Width  | numeric     | 3.5, 3, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, ...
#> Petal.Length | numeric     | 1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, ...   
#> Petal.Width  | numeric     | 0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, ...   
#> Species      | categorical | setosa, setosa, setosa, setosa, ...
str(iris)
#> 'data.frame':    150 obs. of  5 variables:
#>  $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
#>  $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
#>  $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
#>  $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
#>  $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...

data(efc)
data_peek(efc)
#> Data frame with 100 rows and 5 columns
#> 
#> Variable | Type        | Values                                        
#> -----------------------------------------------------------------------
#> c12hour  | numeric     | 16, 148, 70, NA, 168, 16, 161, 110, 28, ...   
#> e16sex   | numeric     | 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, ... 
#> e42dep   | categorical | 3, 3, 3, NA, 4, 4, 4, 4, 4, 4, 4, 3, 4, 3, ...
#> c172code | numeric     | 2, 2, 1, 2, 2, 2, 2, 2, NA, 2, 2, 2, 3, 1, ...
#> neg_c_7  | numeric     | 12, 20, 11, 10, 12, 19, 15, 11, 15, 10, ...
str(efc)
#> 'data.frame':    100 obs. of  5 variables:
#>  $ c12hour : num  16 148 70 NA 168 16 161 110 28 40 ...
#>   ..- attr(*, "label")= chr "average number of hours of care per week"
#>  $ e16sex  : num  2 2 2 2 2 2 1 2 2 2 ...
#>   ..- attr(*, "label")= chr "elder's gender"
#>   ..- attr(*, "labels")= Named num [1:2] 1 2
#>   .. ..- attr(*, "names")= chr [1:2] "male" "female"
#>  $ e42dep  : Factor w/ 4 levels "1","2","3","4": 3 3 3 NA 4 4 4 4 4 4 ...
#>   ..- attr(*, "labels")= Named num [1:4] 1 2 3 4
#>   .. ..- attr(*, "names")= chr [1:4] "independent" "slightly dependent" "moderately dependent" "severely dependent"
#>   ..- attr(*, "label")= chr "elder's dependency"
#>  $ c172code: num  2 2 1 2 2 2 2 2 NA 2 ...
#>   ..- attr(*, "label")= chr "carer's level of education"
#>   ..- attr(*, "labels")= Named num [1:3] 1 2 3
#>   .. ..- attr(*, "names")= chr [1:3] "low level of education" "intermediate level of education" "high level of education"
#>  $ neg_c_7 : num  12 20 11 10 12 19 15 11 15 10 ...
#>   ..- attr(*, "label")= chr "Negative impact with 7 items"
```

<sup>Created on 2022-09-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Review by bwiernik — APPROVED** [review]

**Comment by strengejacke** [comment]
even w/o label attributes it still looks a bit nicer.

``` r
library(datawizard)
data(efc)
data_peek(to_factor(efc, select = c("e16sex", "c172code")))
#> Data frame with 100 rows and 5 columns
#> 
#> Variable | Type        | Values                                        
#> -----------------------------------------------------------------------
#> c12hour  | numeric     | 16, 148, 70, NA, 168, 16, 161, 110, 28, ...   
#> e16sex   | categorical | female, female, female, female, female, ...   
#> e42dep   | categorical | 3, 3, 3, NA, 4, 4, 4, 4, 4, 4, 4, 3, 4, 3, ...
#> c172code | categorical | intermediate level of education, ...          
#> neg_c_7  | numeric     | 12, 20, 11, 10, 12, 19, 15, 11, 15, 10, ...

x <- as.data.frame(lapply(to_factor(efc, select = c("e16sex", "c172code")), function(i) {
  attr(i, "label") <- NULL
  attr(i, "labels") <- NULL
  i
}))
str(x)
#> 'data.frame':    100 obs. of  5 variables:
#>  $ c12hour : num  16 148 70 NA 168 16 161 110 28 40 ...
#>  $ e16sex  : Factor w/ 2 levels "male","female": 2 2 2 2 2 2 1 2 2 2 ...
#>  $ e42dep  : Factor w/ 4 levels "1","2","3","4": 3 3 3 NA 4 4 4 4 4 4 ...
#>  $ c172code: Factor w/ 3 levels "low level of education",..: 2 2 1 2 2 2 2 2 NA 2 ...
#>  $ neg_c_7 : num  12 20 11 10 12 19 15 11 15 10 ...
```

<sup>Created on 2022-09-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
Yes, we could add an argument to have this included, but I wouldn't do so by default, because the idea is actually similar to `glimpse()`, i.e. seeing values.

**Comment by etiennebacher** [comment]
I like the output, it's clearer than `str()`, but I thought the goal of `datawizard` was not to reproduce the tidyverse functions but rather to provide functions that are used in the other `easystats` packages. Is this function needed if the other packages? If not, what are its benefits compared to `dplyr::glimpse()`?

I don't want to sound too much hostile towards this feature 😅 I just remember there was some discussion about copying the dplyr/tidyr functions so I think it's useful to talk about this here.

**Comment by strengejacke** [comment]
Yes, you're right. However, we also have some "tool" functions in _datawizard_ that are not used by other packages, mainly those about data properties:

https://easystats.github.io/datawizard/reference/data_tabulate.html
https://easystats.github.io/datawizard/reference/describe_distribution.html
etc.

I thought this could complement that set of functions... But: I'm ok if we decide _not_ to include this function, it was rather a quick draft and I'm open for discussing this.

**Comment by IndrajeetPatil** [comment]
Thanks, @strengejacke, this looks great!

I also remember the discussion about adding new functionality, but even more important that not just copy-pasting _tidyverse_ functionality is that our ecosystem be self-sufficient, even if this means that we introduce some functions which are not used in the ecosystem. 

If _datawizard_ has functions to import and wrangle data, it makes sense to also have a function to glimpse the data to make sure that it all looks good. Users shouldn't need to use `dplyr::glimpse()` only for this.

**Review by IndrajeetPatil — APPROVED** [review]

**Comment by rempsyc** [comment]
Talking for myself and my own packages, but if I have to rely on `datawizard` _anyway_, and on top of that I can get rid of the `dplyr` dependency (even if it doesn't cover all cases)? Hell yeah, sign me in.

**Pull request merged**
