### PR TITLE
Release 0.13.0

### LINKED ISSUE #543: Preparing CRAN submission
@etiennebacher I plan to submit _insight_ shortly, which will require some packages to be submitted afterwards due to "breaking" changes (deprecation of older arguments). Among these packages is _bayestestR_, which in turn needs _datawizard_ to be on CRAN first (see https://github.com/easystats/datawizard/commit/8ac3a93832f2ab7dc10b48bc6ff861a774e432c7).

There's nothing special to do, except submitting, this is actually independent from _insight_ (must only go before _bayestestR_). Are you available the next days to submit to CRAN?

### PR DESCRIPTION
**Pull request by etiennebacher**
Close #543

### CODE REVIEW

**Comment by strengejacke** [comment]
Maybe wait for #548, so this package makes it into the book :-)
Should be implemented in a few minutes.

**Comment by strengejacke** [comment]
ok, done.

**Comment by strengejacke** [comment]
(sorry, I added a wrong snapshot test, updated the testfile now)

**Comment by etiennebacher** [comment]
Submitted

**Comment by etiennebacher** [comment]
```
ackage datawizard_0.13.0.tar.gz has been auto-processed. The auto-check found problems when checking the first order strong reverse dependencies.
Please reply-all and explain: Is this expected or do you need to fix anything in your package? If expected, have all maintainers of affected packages been informed well in advance? Are there false positives in our results?

*** Changes to worse in reverse dependencies ***
Debian: [<https://win-builder.r-project.org/incoming_pretest/datawizard_0.13.0_20241003_104430/reverseDependencies/summary.txt>](https://win-builder.r-project.org/incoming_pretest/datawizard_0.13.0_20241003_104430/reverseDependencies/summary.txt)
correlation, parameters

Log dir: [<https://win-builder.r-project.org/incoming_pretest/datawizard_0.13.0_20241003_104430/>](https://win-builder.r-project.org/incoming_pretest/datawizard_0.13.0_20241003_104430/)
The files will be removed after roughly 7 days.

Pretests:
Windows: [<https://win-builder.r-project.org/incoming_pretest/datawizard_0.13.0_20241003_104430/Windows/00check.log>](https://win-builder.r-project.org/incoming_pretest/datawizard_0.13.0_20241003_104430/Windows/00check.log)
Debian: [<https://win-builder.r-project.org/incoming_pretest/datawizard_0.13.0_20241003_104430/Debian/00check.log>](https://win-builder.r-project.org/incoming_pretest/datawizard_0.13.0_20241003_104430/Debian/00check.log)

Last published version on CRAN:

CRAN Web: [<https://cran.r-project.org/package=datawizard>](https://cran.r-project.org/package=datawizard)

Best regards,
CRAN teams' auto-check service
Package check result: OK

Changes to worse in reverse depends:

Package: correlation
Check: tests
New result: ERROR
    Running ‘testthat.R’ [19s/19s]
  Running the tests in ‘tests/testthat.R’ failed.
  Complete output:
    > library(testthat)
    > library(correlation)
    >
    > test_check("correlation")

    [ FAIL 6 | WARN 149 | SKIP 13 | PASS 117 ]

    ══ Skipped tests (13) ══════════════════════════════════════════════════════════
    • On CRAN (13): 'test-as.list.r:7:3', 'test-cormatrix_to_excel.r:3:3',
      'test-cormatrix_to_excel.r:16:3', 'test-correlation.r:172:3',
      'test-correlation.r:195:3', 'test-display_print_dataframe.r:2:3',
      'test-display_print_dataframe.r:14:3', 'test-display_print_matrix.r:4:3',
      'test-display_print_matrix.r:13:3', 'test-display_print_matrix.r:31:3',
      'test-methods.r:9:3', 'test-renaming.r:3:3',
      'test-selecting_variables.r:28:3'

    ══ Failed tests ════════════════════════════════════════════════════════════════
    ── Failure ('test-correlation.r:110:3'): format checks ─────────────────────────
    c(nrow(summary(out, redundant = TRUE)), ncol(summary(out, redundant = TRUE))) (`actual`) not identical to c(7L, 8L) (`expected`).

      `actual`: 5 6
    `expected`: 7 8
    ── Failure ('test-correlation.r:111:3'): format checks ─────────────────────────
    c(nrow(summary(out)), ncol(summary(out))) (`actual`) not identical to c(6L, 7L) (`expected`).

      `actual`: 4 5
    `expected`: 6 7
    ── Failure ('test-correlation.r:113:3'): format checks ─────────────────────────
    `out <- correlation(iris, method = "auto", include_factors = TRUE)` did not throw the expected message.
    ── Failure ('test-correlation.r:117:3'): format checks ─────────────────────────
    c(nrow(summary(out, redundant = TRUE)), ncol(summary(out, redundant = TRUE))) (`actual`) not identical to c(7L, 8L) (`expected`).

      `actual`: 5 6
    `expected`: 7 8
    ── Failure ('test-correlation.r:118:3'): format checks ─────────────────────────
    c(nrow(summary(out)), ncol(summary(out))) (`actual`) not identical to c(6L, 7L) (`expected`).

      `actual`: 4 5
    `expected`: 6 7
    ── Failure ('test-correlation.r:120:3'): format checks ─────────────────────────
    all(...) is not TRUE

    `actual`:   FALSE
    `expected`: TRUE

    [ FAIL 6 | WARN 149 | SKIP 13 | PASS 117 ]
    Error: Test failures
    Execution halted

Package: parameters
Check: examples
New result: ERROR
  Running examples in ‘parameters-Ex.R’ failed
  The error most likely occurred in:

  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: reduce_parameters
  > ### Title: Dimensionality reduction (DR) / Features Reduction
  > ### Aliases: reduce_parameters reduce_data
  >
  > ### ** Examples
  >
  > data(iris)
  > model <- lm(Sepal.Width ~ Species * Sepal.Length + Petal.Width, data = iris)
  > model

  Call:
  lm(formula = Sepal.Width ~ Species * Sepal.Length + Petal.Width,
      data = iris)

  Coefficients:
                     (Intercept)               Speciesversicolor
                         -0.4731                          1.2981
                Speciesvirginica                    Sepal.Length
                          1.2252                          0.7515
                     Petal.Width  speciesversicolor:Sepal.Length
                          0.5662                         -0.5503
   speciesvirginica:Sepal.Length
                         -0.5883

  > reduce_parameters(model)
  Error in eval(predvars, data, env) :
    object 'Petal.Width_0.98/Species_0.96/Sepal.Length_0.91' not found
  Calls: reduce_parameters ... eval -> <Anonymous> -> model.frame.default -> eval -> eval
  Execution halted
```

**Comment by etiennebacher** [comment]
I think #547 may have caused failures in revdeps that I forgot to check because I ran it already when I opened this PR...

**Comment by etiennebacher** [comment]
I'll rerun revdepcheck but if all failures are in `easystats` packages, I can just tell them that maintainers are aware and will update their packages?

**Comment by etiennebacher** [comment]
I think you just need to add `dummy_factors = TRUE` in `correlation:::.clean_data()`

**Comment by strengejacke** [comment]
Yes. just saw it and opened a PR.

**Comment by etiennebacher** [comment]
Great, I see you already fixed the issue in parameters as well, thanks! I'll answer them that those failures are known and that we will submit updates for them in the next few weeks

**Comment by etiennebacher** [comment]
0.13.0 is on CRAN

**Pull request merged**
