### PR TITLE
new weighted_mean

### LINKED ISSUE #75: How to deal with robust standardization when mad is 0?
What should we do in such a case?

``` r
mtcars[c("mpg", "am", "hp")] |> 
  datawizard::standardize(robust = TRUE)
#>                             mpg  am         hp
#> Mazda RX4            0.33262558 Inf -0.1686227
#> Mazda RX4 Wag        0.33262558 Inf -0.1686227
#> Datsun 710           0.66525116 Inf -0.3891293
#> Hornet 4 Drive       0.40654238 NaN -0.1686227
#> Hornet Sportabout   -0.09239599 NaN  0.6744908
#> Valiant             -0.20327119 NaN -0.2334776
#> Duster 360          -0.90548075 NaN  1.5824591
#> Merc 240D            0.96091834 NaN -0.7912295
#> Merc 230             0.66525116 NaN -0.3631873
#> Merc 280             0.00000000 NaN  0.0000000
#> Merc 280C           -0.25870878 NaN  0.0000000
#> Merc 450SE          -0.51741757 NaN  0.7393456
#> Merc 450SL          -0.35110478 NaN  0.7393456
#> Merc 450SLC         -0.73916796 NaN  0.7393456
#> Cadillac Fleetwood  -1.62616950 NaN  1.0636200
#> Lincoln Continental -1.62616950 NaN  1.1933298
#> Chrysler Imperial   -0.83156395 NaN  1.3878944
#> Fiat 128             2.43925425 Inf -0.7393456
#> Honda Civic          2.06967028 Inf -0.9209393
#> Toyota Corolla       2.71644224 Inf -0.7523166
#> Toyota Corona        0.42502157 NaN -0.3372454
#> Dodge Challenger    -0.68373036 NaN  0.3502164
#> AMC Javelin         -0.73916796 NaN  0.3502164
#> Camaro Z28          -1.09027273 NaN  1.5824591
#> Pontiac Firebird     0.00000000 NaN  0.6744908
#> Fiat X1-9            1.49681511 Inf -0.7393456
#> Porsche 914-2        1.25658552 Inf -0.4150712
#> Lotus Europa         2.06967028 Inf -0.1297098
#> Ford Pantera L      -0.62829276 Inf  1.8289076
#> Ferrari Dino         0.09239599 Inf  0.6744908
#> Maserati Bora       -0.77612635 Inf  2.7498469
#> Volvo 142E           0.40654238 Inf -0.1815937

mad(mtcars$am)
#> [1] 0
```

<sup>Created on 2022-02-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### PR DESCRIPTION
**Pull request by mattansb**
close #75

### CODE REVIEW

**Comment by mattansb** [comment]
No... 
But I think `datawizard::standardize()` already indirectly tests these?

**Comment by IndrajeetPatil** [comment]
Ah, yes. True.

But I will still add some tests specifically for these functions later.

**Comment by mattansb** [comment]
I see now that these function names clash with `sjstats::weighted_median` and `sjstats::weighted_mean` (@strengejacke)...
Problem?

**Comment by IndrajeetPatil** [comment]
Good catch! Let us know, Daniel, if you want these to be renamed.

**Pull request merged**
