### PR TITLE
simple freq tables

### PR DESCRIPTION
**Pull request by strengejacke**
``` r
library(datawizard)
set.seed(123)
out <- ToothGrowth[sample(1:nrow(ToothGrowth), 50), ]
out$supp[sample(1:nrow(out), 9)] <- NA
out$dose[sample(1:nrow(out), 9)] <- NA
data_table(out[2:3])
#> supp <categorical>
#> # total N=50 valid N=100
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> -------------------------------------------
#> OJ    | 19 | 38.00 |   46.34 |        46.34
#> VC    | 22 | 44.00 |   53.66 |       100.00
#> <NA>  |  9 | 18.00 |    <NA> |         <NA>
#> 
#> dose <numeric>
#> # total N=50 valid N=100
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> -------------------------------------------
#> 0.5   | 15 | 30.00 |   36.59 |        36.59
#> 1     | 12 | 24.00 |   29.27 |        65.85
#> 2     | 14 | 28.00 |   34.15 |       100.00
#> <NA>  |  9 | 18.00 |    <NA> |         <NA>
```

<sup>Created on 2022-04-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### CODE REVIEW

**Comment by strengejacke** [comment]
``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(datawizard)

data(efc)

data_table(efc$e42dep)
#> elder's dependency (efc$e42dep) <categorical>
#> # total N=100 valid N=100
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 1     |  2 |  2.00 |    2.06 |         2.06
#> 2     |  4 |  4.00 |    4.12 |         6.19
#> 3     | 28 | 28.00 |   28.87 |        35.05
#> 4     | 63 | 63.00 |   64.95 |       100.00
#> <NA>  |  3 |  3.00 |    <NA> |         <NA>

data_table(efc, select = c("e16sex", "e4dep"))
#> elder's gender (e16sex) <numeric>
#> # total N=100 valid N=100
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 1     | 46 | 46.00 |   46.00 |        46.00
#> 2     | 54 | 54.00 |   54.00 |       100.00
#> <NA>  |  0 |  0.00 |    <NA> |         <NA>

efc |> 
  group_by(e16sex) |> 
  data_table("c172code")
#> c172code <numeric>
#> Grouped by e16sex (1)
#> # total N=46 valid N=100
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 1     |  5 | 10.87 |   12.20 |        12.20
#> 2     | 32 | 69.57 |   78.05 |        90.24
#> 3     |  4 |  8.70 |    9.76 |       100.00
#> <NA>  |  5 | 10.87 |    <NA> |         <NA>
#> 
#> c172code <numeric>
#> Grouped by e16sex (2)
#> # total N=54 valid N=100
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 1     |  3 |  5.56 |    6.12 |         6.12
#> 2     | 34 | 62.96 |   69.39 |        75.51
#> 3     | 12 | 22.22 |   24.49 |       100.00
#> <NA>  |  5 |  9.26 |    <NA> |         <NA>


efc |> 
  group_by(e16sex) |> 
  data_table(c("c172code", "e42dep"))
#> c172code <numeric>
#> Grouped by e16sex (1)
#> # total N=46 valid N=100
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 1     |  5 | 10.87 |   12.20 |        12.20
#> 2     | 32 | 69.57 |   78.05 |        90.24
#> 3     |  4 |  8.70 |    9.76 |       100.00
#> <NA>  |  5 | 10.87 |    <NA> |         <NA>
#> 
#> e42dep <categorical>
#> Grouped by e16sex (1)
#> # total N=46 valid N=100
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 1     |  2 |  4.35 |    4.44 |         4.44
#> 2     |  2 |  4.35 |    4.44 |         8.89
#> 3     |  8 | 17.39 |   17.78 |        26.67
#> 4     | 33 | 71.74 |   73.33 |       100.00
#> <NA>  |  1 |  2.17 |    <NA> |         <NA>
#> 
#> c172code <numeric>
#> Grouped by e16sex (2)
#> # total N=54 valid N=100
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 1     |  3 |  5.56 |    6.12 |         6.12
#> 2     | 34 | 62.96 |   69.39 |        75.51
#> 3     | 12 | 22.22 |   24.49 |       100.00
#> <NA>  |  5 |  9.26 |    <NA> |         <NA>
#> 
#> e42dep <categorical>
#> Grouped by e16sex (2)
#> # total N=54 valid N=100
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 1     |  0 |  0.00 |    0.00 |         0.00
#> 2     |  2 |  3.70 |    3.85 |         3.85
#> 3     | 20 | 37.04 |   38.46 |        42.31
#> 4     | 30 | 55.56 |   57.69 |       100.00
#> <NA>  |  2 |  3.70 |    <NA> |         <NA>


efc |> 
  group_by(e16sex, c172code) |> 
  data_table("e42dep")
#> e42dep <categorical>
#> Grouped by e16sex (1), c172code (1)
#> # total N=5 valid N=100
#> 
#> Value | N | Raw % | Valid % | Cumulative %
#> ------+---+-------+---------+-------------
#> 1     | 0 |  0.00 |    0.00 |         0.00
#> 2     | 0 |  0.00 |    0.00 |         0.00
#> 3     | 2 | 40.00 |   40.00 |        40.00
#> 4     | 3 | 60.00 |   60.00 |       100.00
#> <NA>  | 0 |  0.00 |    <NA> |         <NA>
#> 
#> e42dep <categorical>
#> Grouped by e16sex (1), c172code (2)
#> # total N=32 valid N=100
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 1     |  2 |  6.25 |    6.25 |         6.25
#> 2     |  2 |  6.25 |    6.25 |        12.50
#> 3     |  4 | 12.50 |   12.50 |        25.00
#> 4     | 24 | 75.00 |   75.00 |       100.00
#> <NA>  |  0 |  0.00 |    <NA> |         <NA>
#> 
#> e42dep <categorical>
#> Grouped by e16sex (1), c172code (3)
#> # total N=4 valid N=100
#> 
#> Value | N | Raw % | Valid % | Cumulative %
#> ------+---+-------+---------+-------------
#> 1     | 0 |  0.00 |    0.00 |         0.00
#> 2     | 0 |  0.00 |    0.00 |         0.00
#> 3     | 1 | 25.00 |   25.00 |        25.00
#> 4     | 3 | 75.00 |   75.00 |       100.00
#> <NA>  | 0 |  0.00 |    <NA> |         <NA>
#> 
#> e42dep <categorical>
#> Grouped by e16sex (1), c172code (NA)
#> # total N=5 valid N=100
#> 
#> Value | N | Raw % | Valid % | Cumulative %
#> ------+---+-------+---------+-------------
#> 1     | 0 |  0.00 |    0.00 |         0.00
#> 2     | 0 |  0.00 |    0.00 |         0.00
#> 3     | 1 | 20.00 |   25.00 |        25.00
#> 4     | 3 | 60.00 |   75.00 |       100.00
#> <NA>  | 1 | 20.00 |    <NA> |         <NA>
#> 
#> e42dep <categorical>
#> Grouped by e16sex (2), c172code (1)
#> # total N=3 valid N=100
#> 
#> Value | N | Raw % | Valid % | Cumulative %
#> ------+---+-------+---------+-------------
#> 1     | 0 |  0.00 |    0.00 |         0.00
#> 2     | 0 |  0.00 |    0.00 |         0.00
#> 3     | 2 | 66.67 |   66.67 |        66.67
#> 4     | 1 | 33.33 |   33.33 |       100.00
#> <NA>  | 0 |  0.00 |    <NA> |         <NA>
#> 
#> e42dep <categorical>
#> Grouped by e16sex (2), c172code (2)
#> # total N=34 valid N=100
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 1     |  0 |  0.00 |    0.00 |         0.00
#> 2     |  2 |  5.88 |    6.25 |         6.25
#> 3     | 12 | 35.29 |   37.50 |        43.75
#> 4     | 18 | 52.94 |   56.25 |       100.00
#> <NA>  |  2 |  5.88 |    <NA> |         <NA>
#> 
#> e42dep <categorical>
#> Grouped by e16sex (2), c172code (3)
#> # total N=12 valid N=100
#> 
#> Value | N | Raw % | Valid % | Cumulative %
#> ------+---+-------+---------+-------------
#> 1     | 0 |  0.00 |    0.00 |         0.00
#> 2     | 0 |  0.00 |    0.00 |         0.00
#> 3     | 5 | 41.67 |   41.67 |        41.67
#> 4     | 7 | 58.33 |   58.33 |       100.00
#> <NA>  | 0 |  0.00 |    <NA> |         <NA>
#> 
#> e42dep <categorical>
#> Grouped by e16sex (2), c172code (NA)
#> # total N=5 valid N=100
#> 
#> Value | N | Raw % | Valid % | Cumulative %
#> ------+---+-------+---------+-------------
#> 1     | 0 |  0.00 |    0.00 |         0.00
#> 2     | 0 |  0.00 |    0.00 |         0.00
#> 3     | 1 | 20.00 |   20.00 |        20.00
#> 4     | 4 | 80.00 |   80.00 |       100.00
#> <NA>  | 0 |  0.00 |    <NA> |         <NA>
```

<sup>Created on 2022-04-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
# For unlabelled data

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(datawizard)

data(efc)
efc <- sjlabelled::remove_all_labels(efc)

data_table(efc$e42dep)
#> efc$e42dep <categorical>
#> # total N=100 valid N=100
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 1     |  2 |  2.00 |    2.06 |         2.06
#> 2     |  4 |  4.00 |    4.12 |         6.19
#> 3     | 28 | 28.00 |   28.87 |        35.05
#> 4     | 63 | 63.00 |   64.95 |       100.00
#> <NA>  |  3 |  3.00 |    <NA> |         <NA>

data_table(efc, select = c("e16sex", "e42dep"))
#> e16sex <numeric>
#> # total N=100 valid N=100
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 1     | 46 | 46.00 |   46.00 |        46.00
#> 2     | 54 | 54.00 |   54.00 |       100.00
#> <NA>  |  0 |  0.00 |    <NA> |         <NA>
#> 
#> e42dep <categorical>
#> # total N=100 valid N=100
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 1     |  2 |  2.00 |    2.06 |         2.06
#> 2     |  4 |  4.00 |    4.12 |         6.19
#> 3     | 28 | 28.00 |   28.87 |        35.05
#> 4     | 63 | 63.00 |   64.95 |       100.00
#> <NA>  |  3 |  3.00 |    <NA> |         <NA>

efc |> 
  group_by(e16sex) |> 
  data_table("c172code")
#> c172code <numeric>
#> Grouped by e16sex (1)
#> # total N=46 valid N=100
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 1     |  5 | 10.87 |   12.20 |        12.20
#> 2     | 32 | 69.57 |   78.05 |        90.24
#> 3     |  4 |  8.70 |    9.76 |       100.00
#> <NA>  |  5 | 10.87 |    <NA> |         <NA>
#> 
#> c172code <numeric>
#> Grouped by e16sex (2)
#> # total N=54 valid N=100
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 1     |  3 |  5.56 |    6.12 |         6.12
#> 2     | 34 | 62.96 |   69.39 |        75.51
#> 3     | 12 | 22.22 |   24.49 |       100.00
#> <NA>  |  5 |  9.26 |    <NA> |         <NA>


efc |> 
  group_by(e16sex) |> 
  data_table(c("c172code", "e42dep"))
#> c172code <numeric>
#> Grouped by e16sex (1)
#> # total N=46 valid N=100
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 1     |  5 | 10.87 |   12.20 |        12.20
#> 2     | 32 | 69.57 |   78.05 |        90.24
#> 3     |  4 |  8.70 |    9.76 |       100.00
#> <NA>  |  5 | 10.87 |    <NA> |         <NA>
#> 
#> e42dep <categorical>
#> Grouped by e16sex (1)
#> # total N=46 valid N=100
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 1     |  2 |  4.35 |    4.44 |         4.44
#> 2     |  2 |  4.35 |    4.44 |         8.89
#> 3     |  8 | 17.39 |   17.78 |        26.67
#> 4     | 33 | 71.74 |   73.33 |       100.00
#> <NA>  |  1 |  2.17 |    <NA> |         <NA>
#> 
#> c172code <numeric>
#> Grouped by e16sex (2)
#> # total N=54 valid N=100
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 1     |  3 |  5.56 |    6.12 |         6.12
#> 2     | 34 | 62.96 |   69.39 |        75.51
#> 3     | 12 | 22.22 |   24.49 |       100.00
#> <NA>  |  5 |  9.26 |    <NA> |         <NA>
#> 
#> e42dep <categorical>
#> Grouped by e16sex (2)
#> # total N=54 valid N=100
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 1     |  0 |  0.00 |    0.00 |         0.00
#> 2     |  2 |  3.70 |    3.85 |         3.85
#> 3     | 20 | 37.04 |   38.46 |        42.31
#> 4     | 30 | 55.56 |   57.69 |       100.00
#> <NA>  |  2 |  3.70 |    <NA> |         <NA>


efc |> 
  group_by(e16sex, c172code) |> 
  data_table("e42dep")
#> e42dep <categorical>
#> Grouped by e16sex (1), c172code (1)
#> # total N=5 valid N=100
#> 
#> Value | N | Raw % | Valid % | Cumulative %
#> ------+---+-------+---------+-------------
#> 1     | 0 |  0.00 |    0.00 |         0.00
#> 2     | 0 |  0.00 |    0.00 |         0.00
#> 3     | 2 | 40.00 |   40.00 |        40.00
#> 4     | 3 | 60.00 |   60.00 |       100.00
#> <NA>  | 0 |  0.00 |    <NA> |         <NA>
#> 
#> e42dep <categorical>
#> Grouped by e16sex (1), c172code (2)
#> # total N=32 valid N=100
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 1     |  2 |  6.25 |    6.25 |         6.25
#> 2     |  2 |  6.25 |    6.25 |        12.50
#> 3     |  4 | 12.50 |   12.50 |        25.00
#> 4     | 24 | 75.00 |   75.00 |       100.00
#> <NA>  |  0 |  0.00 |    <NA> |         <NA>
#> 
#> e42dep <categorical>
#> Grouped by e16sex (1), c172code (3)
#> # total N=4 valid N=100
#> 
#> Value | N | Raw % | Valid % | Cumulative %
#> ------+---+-------+---------+-------------
#> 1     | 0 |  0.00 |    0.00 |         0.00
#> 2     | 0 |  0.00 |    0.00 |         0.00
#> 3     | 1 | 25.00 |   25.00 |        25.00
#> 4     | 3 | 75.00 |   75.00 |       100.00
#> <NA>  | 0 |  0.00 |    <NA> |         <NA>
#> 
#> e42dep <categorical>
#> Grouped by e16sex (1), c172code (NA)
#> # total N=5 valid N=100
#> 
#> Value | N | Raw % | Valid % | Cumulative %
#> ------+---+-------+---------+-------------
#> 1     | 0 |  0.00 |    0.00 |         0.00
#> 2     | 0 |  0.00 |    0.00 |         0.00
#> 3     | 1 | 20.00 |   25.00 |        25.00
#> 4     | 3 | 60.00 |   75.00 |       100.00
#> <NA>  | 1 | 20.00 |    <NA> |         <NA>
#> 
#> e42dep <categorical>
#> Grouped by e16sex (2), c172code (1)
#> # total N=3 valid N=100
#> 
#> Value | N | Raw % | Valid % | Cumulative %
#> ------+---+-------+---------+-------------
#> 1     | 0 |  0.00 |    0.00 |         0.00
#> 2     | 0 |  0.00 |    0.00 |         0.00
#> 3     | 2 | 66.67 |   66.67 |        66.67
#> 4     | 1 | 33.33 |   33.33 |       100.00
#> <NA>  | 0 |  0.00 |    <NA> |         <NA>
#> 
#> e42dep <categorical>
#> Grouped by e16sex (2), c172code (2)
#> # total N=34 valid N=100
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 1     |  0 |  0.00 |    0.00 |         0.00
#> 2     |  2 |  5.88 |    6.25 |         6.25
#> 3     | 12 | 35.29 |   37.50 |        43.75
#> 4     | 18 | 52.94 |   56.25 |       100.00
#> <NA>  |  2 |  5.88 |    <NA> |         <NA>
#> 
#> e42dep <categorical>
#> Grouped by e16sex (2), c172code (3)
#> # total N=12 valid N=100
#> 
#> Value | N | Raw % | Valid % | Cumulative %
#> ------+---+-------+---------+-------------
#> 1     | 0 |  0.00 |    0.00 |         0.00
#> 2     | 0 |  0.00 |    0.00 |         0.00
#> 3     | 5 | 41.67 |   41.67 |        41.67
#> 4     | 7 | 58.33 |   58.33 |       100.00
#> <NA>  | 0 |  0.00 |    <NA> |         <NA>
#> 
#> e42dep <categorical>
#> Grouped by e16sex (2), c172code (NA)
#> # total N=5 valid N=100
#> 
#> Value | N | Raw % | Valid % | Cumulative %
#> ------+---+-------+---------+-------------
#> 1     | 0 |  0.00 |    0.00 |         0.00
#> 2     | 0 |  0.00 |    0.00 |         0.00
#> 3     | 1 | 20.00 |   20.00 |        20.00
#> 4     | 4 | 80.00 |   80.00 |       100.00
#> <NA>  | 0 |  0.00 |    <NA> |         <NA>
```

<sup>Created on 2022-04-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
`data_table()` ok as name? @DominiqueMakowski

**Comment by IndrajeetPatil** [comment]
> data_table() ok as name?

How about ` data_frequency_table()`? 
I am worried that the current name suggests possible association with the `{data.table}` package. But maybe that's just me.

**Comment by strengejacke** [comment]
> I am worried that the current name suggests possible association with the `{data.table}` package.

Yeah, I thought about this, too. But on the other hand, it's a "wrapper" around `table()`, and we use the `data` prefix, hence `data_table()` :-) `data_frequency_table()` is rather long.

**Comment by IndrajeetPatil** [comment]
> data_frequency_table() is rather long

Only if you don't use an IDE ;) Otherwise, auto-completion will take care of it.

**Comment by strengejacke** [comment]
Or `data_tabulate()`?

**Comment by IndrajeetPatil** [comment]
Yeah, that sounds better!

**Pull request merged**
