### PR TITLE
Close #31

### LINKED ISSUE #31: Modulation of appending/overwriting standardized variables in `standardize()` not working
Related to #30 

``` r
d <- iris[1:4, ]

## NOT WORKING
# this should only return the two standardized variables, including suffix
datawizard::standardise(d, select = c("Sepal.Length", "Sepal.Width"), append = FALSE, suffix = "_z")
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1    1.2402159   1.3887301          1.4         0.2  setosa
#> 2    0.3382407  -0.9258201          1.4         0.2  setosa
#> 3   -0.5637345   0.0000000          1.3         0.2  setosa
#> 4   -1.0147221  -0.4629100          1.5         0.2  setosa

## working
# this should return the original data frame and column bound 
# the standardized variables, including suffix
datawizard::standardise(d, select = c("Sepal.Length", "Sepal.Width"), append = TRUE, suffix = "_z")
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species Sepal.Length_z
#> 1          5.1         3.5          1.4         0.2  setosa      1.2402159
#> 2          4.9         3.0          1.4         0.2  setosa      0.3382407
#> 3          4.7         3.2          1.3         0.2  setosa     -0.5637345
#> 4          4.6         3.1          1.5         0.2  setosa     -1.0147221
#>   Sepal.Width_z
#> 1     1.3887301
#> 2    -0.9258201
#> 3     0.0000000
#> 4    -0.4629100

## NOT WORKING
# this should only return the standardized variables, w/o suffix
datawizard::standardise(d, select = c("Sepal.Length", "Sepal.Width"), append = FALSE, suffix = NULL)
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1    1.2402159   1.3887301          1.4         0.2  setosa
#> 2    0.3382407  -0.9258201          1.4         0.2  setosa
#> 3   -0.5637345   0.0000000          1.3         0.2  setosa
#> 4   -1.0147221  -0.4629100          1.5         0.2  setosa

## NOT WORKING
# this should return the original data frame and the the standardized variables
# *overwrite* the related variables
datawizard::standardise(d, select = c("Sepal.Length", "Sepal.Width"), append = TRUE, suffix = NULL)
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species Sepal.Length
#> 1    1.2402159   1.3887301          1.4         0.2  setosa          5.1
#> 2    0.3382407  -0.9258201          1.4         0.2  setosa          4.9
#> 3   -0.5637345   0.0000000          1.3         0.2  setosa          4.7
#> 4   -1.0147221  -0.4629100          1.5         0.2  setosa          4.6
#>   Sepal.Width
#> 1         3.5
#> 2         3.0
#> 3         3.2
#> 4         3.1
```

<sup>Created on 2021-11-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### PR DESCRIPTION
**Pull request by strengejacke**

### CODE REVIEW

**Comment by strengejacke** [comment]
``` r
d <- iris[1:4, ]

# append
datawizard::standardise(d, select = c("Sepal.Length", "Sepal.Width"), suffix = "_z")
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species Sepal.Length_z
#> 1          5.1         3.5          1.4         0.2  setosa      1.2402159
#> 2          4.9         3.0          1.4         0.2  setosa      0.3382407
#> 3          4.7         3.2          1.3         0.2  setosa     -0.5637345
#> 4          4.6         3.1          1.5         0.2  setosa     -1.0147221
#>   Sepal.Width_z
#> 1     1.3887301
#> 2    -0.9258201
#> 3     0.0000000
#> 4    -0.4629100

# overwrite
datawizard::standardise(d, select = c("Sepal.Length", "Sepal.Width"), suffix = NULL)
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1    1.2402159   1.3887301          1.4         0.2  setosa
#> 2    0.3382407  -0.9258201          1.4         0.2  setosa
#> 3   -0.5637345   0.0000000          1.3         0.2  setosa
#> 4   -1.0147221  -0.4629100          1.5         0.2  setosa
```

<sup>Created on 2021-11-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
This PR implements the original intention from @DominiqueMakowski (see #30). Unless we want a more flexible behaviour (see #31), this could be merged.

**Comment by bwiernik** [comment]
I think we merge this. In my view, the expected behavior for standardize.data.frame would be to standardize the requested variables and return the full data frame. Other behavior can be accomplished with `dplyr::transmute()` or `with()`.

**Review by bwiernik — APPROVED** [review]

**Comment by strengejacke** [comment]
``` r
library(datawizard)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

d <- iris[1:4, ]

# overwrite
standardise(d, select = c("Sepal.Length", "Sepal.Width"))
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1    1.2402159   1.3887301          1.4         0.2  setosa
#> 2    0.3382407  -0.9258201          1.4         0.2  setosa
#> 3   -0.5637345   0.0000000          1.3         0.2  setosa
#> 4   -1.0147221  -0.4629100          1.5         0.2  setosa

# append
standardise(d, select = c("Sepal.Length", "Sepal.Width"), append = TRUE)
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species Sepal.Length_z
#> 1          5.1         3.5          1.4         0.2  setosa      1.2402159
#> 2          4.9         3.0          1.4         0.2  setosa      0.3382407
#> 3          4.7         3.2          1.3         0.2  setosa     -0.5637345
#> 4          4.6         3.1          1.5         0.2  setosa     -1.0147221
#>   Sepal.Width_z
#> 1     1.3887301
#> 2    -0.9258201
#> 3     0.0000000
#> 4    -0.4629100

# append, suffix
standardise(d, select = c("Sepal.Length", "Sepal.Width"), append = "_std")
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species Sepal.Length_std
#> 1          5.1         3.5          1.4         0.2  setosa        1.2402159
#> 2          4.9         3.0          1.4         0.2  setosa        0.3382407
#> 3          4.7         3.2          1.3         0.2  setosa       -0.5637345
#> 4          4.6         3.1          1.5         0.2  setosa       -1.0147221
#>   Sepal.Width_std
#> 1       1.3887301
#> 2      -0.9258201
#> 3       0.0000000
#> 4      -0.4629100


# grouped

d <- iris[c(1:3, 51:53, 101:103), ]

# overwrite
d |> 
  standardise(select = c("Sepal.Length", "Sepal.Width"))
#>     Sepal.Length Sepal.Width Petal.Length Petal.Width    Species
#> 1     -0.9848034   1.6397832          1.4         0.2     setosa
#> 2     -1.1983752  -0.5962848          1.4         0.2     setosa
#> 3     -1.4119471   0.2981424          1.3         0.2     setosa
#> 51     1.0441289   0.2981424          4.7         1.4 versicolor
#> 52     0.4034134   0.2981424          4.5         1.5 versicolor
#> 53     0.9373430  -0.1490712          4.9         1.5 versicolor
#> 101    0.2966275   0.7453560          6.0         2.5  virginica
#> 102   -0.2373020  -1.9379256          5.1         1.9  virginica
#> 103    1.1509148  -0.5962848          5.9         2.1  virginica

d |> 
  group_by(Species) |> 
  standardise(select = c("Sepal.Length", "Sepal.Width")) |> 
  as.data.frame()
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width    Species
#> 1    1.0000000   1.0596259          1.4         0.2     setosa
#> 2    0.0000000  -0.9271726          1.4         0.2     setosa
#> 3   -1.0000000  -0.1324532          1.3         0.2     setosa
#> 4    0.7258662   0.5773503          4.7         1.4 versicolor
#> 5   -1.1406469   0.5773503          4.5         1.5 versicolor
#> 6    0.4147807  -1.1547005          4.9         1.5 versicolor
#> 7   -0.1524986   1.0000000          6.0         2.5  virginica
#> 8   -0.9149914  -1.0000000          5.1         1.9  virginica
#> 9    1.0674900   0.0000000          5.9         2.1  virginica

# append
d |> 
  standardise(select = c("Sepal.Length", "Sepal.Width"), append = TRUE)
#>     Sepal.Length Sepal.Width Petal.Length Petal.Width    Species Sepal.Length_z
#> 1            5.1         3.5          1.4         0.2     setosa     -0.9848034
#> 2            4.9         3.0          1.4         0.2     setosa     -1.1983752
#> 3            4.7         3.2          1.3         0.2     setosa     -1.4119471
#> 51           7.0         3.2          4.7         1.4 versicolor      1.0441289
#> 52           6.4         3.2          4.5         1.5 versicolor      0.4034134
#> 53           6.9         3.1          4.9         1.5 versicolor      0.9373430
#> 101          6.3         3.3          6.0         2.5  virginica      0.2966275
#> 102          5.8         2.7          5.1         1.9  virginica     -0.2373020
#> 103          7.1         3.0          5.9         2.1  virginica      1.1509148
#>     Sepal.Width_z
#> 1       1.6397832
#> 2      -0.5962848
#> 3       0.2981424
#> 51      0.2981424
#> 52      0.2981424
#> 53     -0.1490712
#> 101     0.7453560
#> 102    -1.9379256
#> 103    -0.5962848

d |> 
  group_by(Species) |> 
  standardise(select = c("Sepal.Length", "Sepal.Width"), append = TRUE) |> 
  as.data.frame()
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width    Species Sepal.Length_z
#> 1          5.1         3.5          1.4         0.2     setosa      1.0000000
#> 2          4.9         3.0          1.4         0.2     setosa      0.0000000
#> 3          4.7         3.2          1.3         0.2     setosa     -1.0000000
#> 4          7.0         3.2          4.7         1.4 versicolor      0.7258662
#> 5          6.4         3.2          4.5         1.5 versicolor     -1.1406469
#> 6          6.9         3.1          4.9         1.5 versicolor      0.4147807
#> 7          6.3         3.3          6.0         2.5  virginica     -0.1524986
#> 8          5.8         2.7          5.1         1.9  virginica     -0.9149914
#> 9          7.1         3.0          5.9         2.1  virginica      1.0674900
#>   Sepal.Width_z
#> 1     1.0596259
#> 2    -0.9271726
#> 3    -0.1324532
#> 4     0.5773503
#> 5     0.5773503
#> 6    -1.1547005
#> 7     1.0000000
#> 8    -1.0000000
#> 9     0.0000000

# append, suffix
d |> 
  standardise(select = c("Sepal.Length", "Sepal.Width"), append = "_std")
#>     Sepal.Length Sepal.Width Petal.Length Petal.Width    Species
#> 1            5.1         3.5          1.4         0.2     setosa
#> 2            4.9         3.0          1.4         0.2     setosa
#> 3            4.7         3.2          1.3         0.2     setosa
#> 51           7.0         3.2          4.7         1.4 versicolor
#> 52           6.4         3.2          4.5         1.5 versicolor
#> 53           6.9         3.1          4.9         1.5 versicolor
#> 101          6.3         3.3          6.0         2.5  virginica
#> 102          5.8         2.7          5.1         1.9  virginica
#> 103          7.1         3.0          5.9         2.1  virginica
#>     Sepal.Length_std Sepal.Width_std
#> 1         -0.9848034       1.6397832
#> 2         -1.1983752      -0.5962848
#> 3         -1.4119471       0.2981424
#> 51         1.0441289       0.2981424
#> 52         0.4034134       0.2981424
#> 53         0.9373430      -0.1490712
#> 101        0.2966275       0.7453560
#> 102       -0.2373020      -1.9379256
#> 103        1.1509148      -0.5962848

d |> 
  group_by(Species) |> 
  standardise(select = c("Sepal.Length", "Sepal.Width"), append = "_std") |> 
  as.data.frame()
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width    Species Sepal.Length_std
#> 1          5.1         3.5          1.4         0.2     setosa        1.0000000
#> 2          4.9         3.0          1.4         0.2     setosa        0.0000000
#> 3          4.7         3.2          1.3         0.2     setosa       -1.0000000
#> 4          7.0         3.2          4.7         1.4 versicolor        0.7258662
#> 5          6.4         3.2          4.5         1.5 versicolor       -1.1406469
#> 6          6.9         3.1          4.9         1.5 versicolor        0.4147807
#> 7          6.3         3.3          6.0         2.5  virginica       -0.1524986
#> 8          5.8         2.7          5.1         1.9  virginica       -0.9149914
#> 9          7.1         3.0          5.9         2.1  virginica        1.0674900
#>   Sepal.Width_std
#> 1       1.0596259
#> 2      -0.9271726
#> 3      -0.1324532
#> 4       0.5773503
#> 5       0.5773503
#> 6      -1.1547005
#> 7       1.0000000
#> 8      -1.0000000
#> 9       0.0000000
```

<sup>Created on 2021-11-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Pull request merged**
