### PR TITLE
Release 0.7.0

### PR DESCRIPTION
**Pull request by etiennebacher**
https://github.com/easystats/workflows/issues/21

### CODE REVIEW

**Comment by etiennebacher** [comment]
For some reason `revdepcheck` didn't work: I have errors in tests of `report`

**Comment by strengejacke** [comment]
Can you point out which errors?

**Comment by etiennebacher** [comment]
``` r
library(report)

model <- anova(lm(Sepal.Width ~ Species, data = iris))
report(model)
#> Error in switch(type, `:` = .select_seq(x, data, ignore_case, regex, verbose), : EXPR must be a length 1 vector
```

I think I know where to fix it in `report`

**Comment by etiennebacher** [comment]
Too late, I answered the CRAN team this afternoon about the revdep failure (now fixed) and datawizard 0.7.0 is now on CRAN

**Comment by IndrajeetPatil** [comment]
No worries.

**Pull request merged**
