### PR TITLE
rename weights parameter

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
more verbose is better for the users; similar to sjstats

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
There is slight difference between `weighted_median()` values between these two packages:

``` r
library(sjstats)

x <- c(3.7, 3.3, 3.5, 2.8)
wt <- c(5,  5,  4,  1)/15

weighted_mean(x, wt)
#> [1] 3.453333
weighted_median(x, wt)
#> [1] 3.5
```

<sup>Created on 2022-03-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

``` r
library(datawizard)

x <- c(3.7, 3.3, 3.5, 2.8)
wt <- c(5,  5,  4,  1)/15

weighted_mean(x, wt)
#> [1] 3.453333
weighted_median(x, wt)
#> [1] 3.653333
```

<sup>Created on 2022-03-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by strengejacke** [comment]
Here's another one:

``` r
x <- c(3.7, 3.3, 3.5, 2.8)
wt <- c(5,  5,  4,  1)/15
matrixStats::weightedMedian(x, wt)
#> [1] 3.477778

matrixStats::weightedMedian(x, wt, ties = "mean")
#> [1] 3.5
```

<sup>Created on 2022-03-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
``` r
x <- c(3.7, 3.3, 3.5, 2.8)
wt <- c(5,  5,  4,  1)/15

ergm::wtd.median(x = x, weight = wt)
#> [1] 3.5
```

<sup>Created on 2022-03-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by IndrajeetPatil** [comment]
Hmm, so something unusual is happening _datawizard_'s implementation

**Comment by mattansb** [comment]
Feel free to change the code for median/mad as you see fit - I tried to implant something from Wikipedia, might have done it wrong 🤷‍♂️🤦‍♂️

**Comment by IndrajeetPatil** [comment]
Okay, will handle this in a separate PR since this one is mostly about renaming the parameter.

**Pull request merged**
