### PR TITLE
Implement `means_by_group()`

### PR DESCRIPTION
**Pull request by strengejacke**
- [x] check whether value labels for `group` are preserved

### CODE REVIEW

**Comment by strengejacke** [comment]
@mattansb @bwiernik @etiennebacher Do you know how to get the p-value that is returned by the emmeans-code? I can get the p-value by changing the contrasts for the factor, but that's a bit complicated to compute the model twice. Is there an easy base-R way that does not rely on emmeans?

``` r
data(iris)
m <- lm(Sepal.Length ~ Species, data = iris)
summary(m)
#> 
#> Call:
#> lm(formula = Sepal.Length ~ Species, data = iris)
#> 
#> Residuals:
#>     Min      1Q  Median      3Q     Max 
#> -1.6880 -0.3285 -0.0060  0.3120  1.3120 
#> 
#> Coefficients:
#>                   Estimate Std. Error t value Pr(>|t|)    
#> (Intercept)         5.0060     0.0728  68.762  < 2e-16 ***
#> Speciesversicolor   0.9300     0.1030   9.033 8.77e-16 ***
#> Speciesvirginica    1.5820     0.1030  15.366  < 2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> Residual standard error: 0.5148 on 147 degrees of freedom
#> Multiple R-squared:  0.6187, Adjusted R-squared:  0.6135 
#> F-statistic: 119.3 on 2 and 147 DF,  p-value: < 2.2e-16
emmeans::emmeans(m, "Species") |> emmeans::contrast(method = "eff")
#>  contrast          estimate     SE  df t.ratio p.value
#>  setosa effect      -0.8373 0.0594 147 -14.086  <.0001
#>  versicolor effect   0.0927 0.0594 147   1.559  0.1212
#>  virginica effect    0.7447 0.0594 147  12.527  <.0001
#> 
#> P value adjustment: fdr method for 3 tests

contrasts(iris$Species) <- contr.sum
m <- lm(Sepal.Length ~ Species, data = iris)
summary(m)
#> 
#> Call:
#> lm(formula = Sepal.Length ~ Species, data = iris)
#> 
#> Residuals:
#>     Min      1Q  Median      3Q     Max 
#> -1.6880 -0.3285 -0.0060  0.3120  1.3120 
#> 
#> Coefficients:
#>             Estimate Std. Error t value Pr(>|t|)    
#> (Intercept)  5.84333    0.04203 139.020   <2e-16 ***
#> Species1    -0.83733    0.05944 -14.086   <2e-16 ***
#> Species2     0.09267    0.05944   1.559    0.121    
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> Residual standard error: 0.5148 on 147 degrees of freedom
#> Multiple R-squared:  0.6187, Adjusted R-squared:  0.6135 
#> F-statistic: 119.3 on 2 and 147 DF,  p-value: < 2.2e-16
```

<sup>Created on 2023-08-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
Current state:

``` r
datawizard::means_by_group(iris$Sepal.Length, iris$Species)
#> # Mean of iris$Sepal.Length by iris$Species
#> 
#> Category   | Mean |   N |   SD
#> ------------------------------
#> setosa     | 5.01 |  50 | 0.35
#> versicolor | 5.94 |  50 | 0.52
#> virginica  | 6.59 |  50 | 0.64
#> Total      | 5.84 | 150 | 0.83
#> 
#> Anova: R2=0.619; adj.R2=0.614; F=119.265; p<.001
datawizard::means_by_group(iris, "Sepal.Length", "Species")
#> [[1]]
#> # Mean of x[[i]] by x[[group]]
#> 
#> Category   | Mean |   N |   SD
#> ------------------------------
#> setosa     | 5.01 |  50 | 0.35
#> versicolor | 5.94 |  50 | 0.52
#> virginica  | 6.59 |  50 | 0.64
#> Total      | 5.84 | 150 | 0.83
#> 
#> Anova: R2=0.619; adj.R2=0.614; F=119.265; p<.001
sjstats::means_by_group(iris, Sepal.Length, Species)
#> 
#> # Grouped Means for Sepal.Length by Species
#> 
#> Category   | Mean |   N |   SD |   SE |      p
#> ----------------------------------------------
#> setosa     | 5.01 |  50 | 0.35 | 0.05 | < .001
#> versicolor | 5.94 |  50 | 0.52 | 0.07 |  0.121
#> virginica  | 6.59 |  50 | 0.64 | 0.09 | < .001
#> Total      | 5.84 | 150 | 0.83 | 0.07 |       
#> 
#> Anova: R2=0.619; adj.R2=0.614; F=119.265; p=0.000
```

<sup>Created on 2023-08-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by bwiernik** [comment]
pass the result of `contrast()` to `summary()` or `emmeans::test()` for p values and to `confint()` for CIs.

**Comment by strengejacke** [comment]
> pass the result of `contrast()` to `summary()` or `emmeans::test()` for p values and to `confint()` for CIs.

My aim was to _avoid_ emmeans if possible :-)

**Comment by bwiernik** [comment]
You're already importing emmeans though?

Otherwise, just fit lm() once and specify lm(..., contrasts = list(group = contr.sum))

**Comment by strengejacke** [comment]
> You're already importing emmeans though to get the contrasts?

Yes, and that's what I would like to do otherwise. :-)

**Comment by strengejacke** [comment]
> Otherwise, just fit lm() once and specify lm(..., contrasts = list(group = contr.sum))

Yeah, then I only need to fit the model twice and find the correct coefficients:

``` r
summary(lm(Sepal.Length ~ Species, data = iris, contrasts = list(Species = contr.sum)))
#> 
#> Call:
#> lm(formula = Sepal.Length ~ Species, data = iris, contrasts = list(Species = contr.sum))
#> 
#> Residuals:
#>     Min      1Q  Median      3Q     Max 
#> -1.6880 -0.3285 -0.0060  0.3120  1.3120 
#> 
#> Coefficients:
#>             Estimate Std. Error t value Pr(>|t|)    
#> (Intercept)  5.84333    0.04203 139.020   <2e-16 ***
#> Species1    -0.83733    0.05944 -14.086   <2e-16 ***
#> Species2     0.09267    0.05944   1.559    0.121    
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> Residual standard error: 0.5148 on 147 degrees of freedom
#> Multiple R-squared:  0.6187, Adjusted R-squared:  0.6135 
#> F-statistic: 119.3 on 2 and 147 DF,  p-value: < 2.2e-16
summary(lm(Sepal.Length ~ Species, data = iris))
#> 
#> Call:
#> lm(formula = Sepal.Length ~ Species, data = iris)
#> 
#> Residuals:
#>     Min      1Q  Median      3Q     Max 
#> -1.6880 -0.3285 -0.0060  0.3120  1.3120 
#> 
#> Coefficients:
#>                   Estimate Std. Error t value Pr(>|t|)    
#> (Intercept)         5.0060     0.0728  68.762  < 2e-16 ***
#> Speciesversicolor   0.9300     0.1030   9.033 8.77e-16 ***
#> Speciesvirginica    1.5820     0.1030  15.366  < 2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> Residual standard error: 0.5148 on 147 degrees of freedom
#> Multiple R-squared:  0.6187, Adjusted R-squared:  0.6135 
#> F-statistic: 119.3 on 2 and 147 DF,  p-value: < 2.2e-16
```

<sup>Created on 2023-08-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by bwiernik** [comment]
Why do you need the second fit? Just use contr.sum() once

**Comment by strengejacke** [comment]
Because I need the p-value for all levels, and sum contrasts don't include the last level, treatment contrasts don't include the first (reference) level

**Comment by strengejacke** [comment]
``` r
library(datawizard)
data(efc)
means_by_group(efc, "c12hour", "e42dep")
#> # Mean of average number of hours of care per week by elder's dependency
#> 
#> Category             |   Mean |  N |    SD |           95% CI |      p
#> ----------------------------------------------------------------------
#> independent          |  17.00 |  2 | 11.31 | [-68.46, 102.46] | 0.573 
#> slightly dependent   |  34.25 |  4 | 29.97 | [-26.18,  94.68] | 0.626 
#> moderately dependent |  52.75 | 28 | 51.83 | [ 29.91,  75.59] | > .999
#> severely dependent   | 106.97 | 63 | 65.88 | [ 91.74, 122.19] | 0.001 
#> Total                |  86.46 | 97 | 66.40 |                  |       
#> 
#> Anova: R2=0.186; adj.R2=0.160; F=7.098; p<.001
means_by_group(efc, "c12hour", "e42dep", ci = 0.99)
#> # Mean of average number of hours of care per week by elder's dependency
#> 
#> Category             |   Mean |  N |    SD |           99% CI |      p
#> ----------------------------------------------------------------------
#> independent          |  17.00 |  2 | 11.31 | [-96.17, 130.17] | 0.573 
#> slightly dependent   |  34.25 |  4 | 29.97 | [-45.77, 114.27] | 0.626 
#> moderately dependent |  52.75 | 28 | 51.83 | [ 22.50,  83.00] | > .999
#> severely dependent   | 106.97 | 63 | 65.88 | [ 86.80, 127.13] | 0.001 
#> Total                |  86.46 | 97 | 66.40 |                  |       
#> 
#> Anova: R2=0.186; adj.R2=0.160; F=7.098; p<.001
means_by_group(efc, "c12hour", "e42dep", ci = NA)
#> # Mean of average number of hours of care per week by elder's dependency
#> 
#> Category             |   Mean |  N |    SD |      p
#> ---------------------------------------------------
#> independent          |  17.00 |  2 | 11.31 | 0.573 
#> slightly dependent   |  34.25 |  4 | 29.97 | 0.626 
#> moderately dependent |  52.75 | 28 | 51.83 | > .999
#> severely dependent   | 106.97 | 63 | 65.88 | 0.001 
#> Total                |  86.46 | 97 | 66.40 |       
#> 
#> Anova: R2=0.186; adj.R2=0.160; F=7.098; p<.001
```

<sup>Created on 2023-08-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Review by etiennebacher — APPROVED** [review]
LGTM, thanks @strengejacke

**Comment by bwiernik** [comment]
> Because I need the p-value for all levels, and sum contrasts don't include the last level, treatment contrasts don't include the first (reference) level 

For the last level:

```
last_coef <- `sum(coef(mod)[-1]`
last_se <- sqrt(sum(vcov(mod)[-1,-1])
last_stat <- abs(last_coef) / last_se
last_p <- qt(last_stat, get_dof(mod), lower.tail = FALSE) * 2
```

**Pull request merged**
