### PR TITLE
Make `coerce_to_numeric()` internal

### LINKED ISSUE #206: Consolidate `coerce_to_numeric()` into `to_numeric()` via a new argument

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
Closes #206

I will update `NEWS.md` later.

### CODE REVIEW

**Review by strengejacke — CHANGES_REQUESTED** [review]
This doesn't work, we need to keep `coerce_to_numeric()` at least as internal.

See `data_to_long(mtcars, 2:4)`.

**Comment by IndrajeetPatil** [comment]
It's worrisome that not a single test failed 😐

**Comment by strengejacke** [comment]
> It's worrisome that not a single test failed 😐

Yes, I added a test that should capture this change (hopefully)

**Comment by strengejacke** [comment]
I'm not sure about `data_restoretype()`, though, how to add a test that detects if `as.numeric()` will work or not.

**Comment by strengejacke** [comment]
This would be the **new** behaviour with `as.numeric()`:

``` r
library(datawizard)
data <- data.frame(
  Sepal.Length = c("1", "3", "a"),
  Species = c("setosa", "versicolor", "setosa"),
  New = c("1", "3", "4")
)

fixed <- data_restoretype(data, reference = iris)
#> Warning in data_restoretype(data, reference = iris): NAs introduced by coercion
fixed
#>   Sepal.Length    Species New
#> 1            1     setosa   1
#> 2            3 versicolor   3
#> 3           NA     setosa   4
```

and this the **old** behaviour, when we keep `coerce_to_numeric()` as internal:

``` r
library(datawizard)
data <- data.frame(
  Sepal.Length = c("1", "3", "a"),
  Species = c("setosa", "versicolor", "setosa"),
  New = c("1", "3", "4")
)

fixed <- data_restoretype(data, reference = iris)
fixed
#>   Sepal.Length    Species New
#> 1            1     setosa   1
#> 2            3 versicolor   3
#> 3            a     setosa   4
```

@DominiqueMakowski what would you say is the expected behaviour?

**Comment by strengejacke** [comment]
(we should add the example of the expected behaviour as test)

**Comment by strengejacke** [comment]
> @DominiqueMakowski what would you say is the expected behaviour?

_bump_ 😬

**Comment by IndrajeetPatil** [comment]
*bump*

I want to make a new release soon, since I want the JOSS paper to be based on the more stable API of 0.6.0 instead of the current 0.5.0 release API.

Just so you know in case you want this PR to be part of the next release.

**Comment by IndrajeetPatil** [comment]
Merge conflict.

**Comment by strengejacke** [comment]
> > @DominiqueMakowski what would you say is the expected behaviour?
> 
> _bump_ 😬

hello-mcfly

**Comment by IndrajeetPatil** [comment]
Damn it. Merge conflict again.

**Comment by strengejacke** [comment]
@DominiqueMakowski 

> > > @DominiqueMakowski what would you say is the expected behaviour?
> > 
> > 
> > _bump_ 😬
>

**Pull request closed without merging**
