### PR TITLE
data_codebook

### PR DESCRIPTION
**Pull request by strengejacke**
Function to generate codebooks from data frames.

### CODE REVIEW

**Comment by strengejacke** [comment]
``` r
library(datawizard)
data_codebook(iris)
#> ID |         Name | missings |     Values |   N
#> ---+--------------+----------+------------+----
#> 1  | Sepal.Length | 0 (0.0%) | [4.3, 7.9] | 150
#> ---+--------------+----------+------------+----
#> 2  |  Sepal.Width | 0 (0.0%) |   [2, 4.4] | 150
#> ---+--------------+----------+------------+----
#> 3  | Petal.Length | 0 (0.0%) |   [1, 6.9] | 150
#> ---+--------------+----------+------------+----
#> 4  |  Petal.Width | 0 (0.0%) | [0.1, 2.5] | 150
#> ---+--------------+----------+------------+----
#> 5  |      Species | 0 (0.0%) |     setosa |  50
#>    |              |          | versicolor |  50
#>    |              |          |  virginica |  50
#> -----------------------------------------------

data(iris)
iris$Sepal.Width <- NA
data_codebook(iris)
#> Warning: Following 1 columns were empty and have been removed:
#>   Sepal.Width
#> ID |         Name | missings |     Values |   N
#> ---+--------------+----------+------------+----
#> 1  | Sepal.Length | 0 (0.0%) | [4.3, 7.9] | 150
#> ---+--------------+----------+------------+----
#> 2  | Petal.Length | 0 (0.0%) |   [1, 6.9] | 150
#> ---+--------------+----------+------------+----
#> 3  |  Petal.Width | 0 (0.0%) | [0.1, 2.5] | 150
#> ---+--------------+----------+------------+----
#> 4  |      Species | 0 (0.0%) |     setosa |  50
#>    |              |          | versicolor |  50
#>    |              |          |  virginica |  50
#> -----------------------------------------------

data(efc)
data_codebook(efc)
#> ID |     Name |  missings |                                    Label |   Values |                    Value Labels |  N
#> ---+----------+-----------+------------------------------------------+----------+---------------------------------+---
#> 1  |  c12hour |  2 (0.0%) | average number of hours of care per week | [5, 168] |                                 | 98
#> ---+----------+-----------+------------------------------------------+----------+---------------------------------+---
#> 2  |   e16sex |  0 (0.0%) |                           elder's gender |        1 |                            male | 46
#>    |          |           |                                          |        2 |                          female | 54
#> ---+----------+-----------+------------------------------------------+----------+---------------------------------+---
#> 3  |   e42dep |  3 (0.0%) |                       elder's dependency |        1 |                     independent |  2
#>    |          |           |                                          |        2 |              slightly dependent |  4
#>    |          |           |                                          |        3 |            moderately dependent | 28
#>    |          |           |                                          |        4 |              severely dependent | 63
#> ---+----------+-----------+------------------------------------------+----------+---------------------------------+---
#> 4  | c172code | 10 (0.1%) |               carer's level of education |        1 |          low level of education |  8
#>    |          |           |                                          |        2 | intermediate level of education | 66
#>    |          |           |                                          |        3 |         high level of education | 16
#> ---+----------+-----------+------------------------------------------+----------+---------------------------------+---
#> 5  |  neg_c_7 |  3 (0.0%) |             Negative impact with 7 items |  [7, 28] |                                 | 97
#> ----------------------------------------------------------------------------------------------------------------------

data_codebook(efc, label_width = 30)
#> ID |     Name |  missings |                        Label |   Values |                    Value Labels |  N
#> ---+----------+-----------+------------------------------+----------+---------------------------------+---
#> 1  |  c12hour |  2 (0.0%) |   average number of hours of | [5, 168] |                                 | 98
#>    |          |           |                care per week | [5, 168] |                                 | 98
#> ---+----------+-----------+------------------------------+----------+---------------------------------+---
#> 2  |   e16sex |  0 (0.0%) |               elder's gender |        1 |                            male | 46
#>    |          |           |                              |        2 |                          female | 54
#> ---+----------+-----------+------------------------------+----------+---------------------------------+---
#> 3  |   e42dep |  3 (0.0%) |           elder's dependency |        1 |                     independent |  2
#>    |          |           |                              |        2 |              slightly dependent |  4
#>    |          |           |                              |        3 |            moderately dependent | 28
#>    |          |           |                              |        4 |              severely dependent | 63
#> ---+----------+-----------+------------------------------+----------+---------------------------------+---
#> 4  | c172code | 10 (0.1%) |   carer's level of education |        1 |          low level of education |  8
#>    |          |           |                              |        2 | intermediate level of education | 66
#>    |          |           |                              |        3 |         high level of education | 16
#> ---+----------+-----------+------------------------------+----------+---------------------------------+---
#> 5  |  neg_c_7 |  3 (0.0%) | Negative impact with 7 items |  [7, 28] |                                 | 97
#> ----------------------------------------------------------------------------------------------------------

x <- data_codebook(efc)
print_md(x)
```

| ID  |     Name |  missings | Label                                    | Values     |                    Value Labels | N   |
|:----|---------:|----------:|:-----------------------------------------|:-----------|--------------------------------:|:----|
| 1   |  c12hour |  2 (0.0%) | average number of hours of care per week | \[5, 168\] |                                 | 98  |
|     |          |           |                                          |            |                                 |     |
| 2   |   e16sex |  0 (0.0%) | elder’s gender                           | 1          |                            male | 46  |
|     |          |           |                                          | 2          |                          female | 54  |
|     |          |           |                                          |            |                                 |     |
| 3   |   e42dep |  3 (0.0%) | elder’s dependency                       | 1          |                     independent | 2   |
|     |          |           |                                          | 2          |              slightly dependent | 4   |
|     |          |           |                                          | 3          |            moderately dependent | 28  |
|     |          |           |                                          | 4          |              severely dependent | 63  |
|     |          |           |                                          |            |                                 |     |
| 4   | c172code | 10 (0.1%) | carer’s level of education               | 1          |          low level of education | 8   |
|     |          |           |                                          | 2          | intermediate level of education | 66  |
|     |          |           |                                          | 3          |         high level of education | 16  |
|     |          |           |                                          |            |                                 |     |
| 5   | neg_c\_7 |  3 (0.0%) | Negative impact with 7 items             | \[7, 28\]  |                                 | 97  |
|     |          |           |                                          |            |                                 |     |

**Comment by strengejacke** [comment]
For shortened variable labels (when `label_width` is used), if variable is numeric w/o value labels, the value range and N is duplicated. That must be fixed.

**Comment by strengejacke** [comment]
``` r
library(datawizard)
data_codebook(iris)
#> iris (total N=150)
#> 
#> ID |         Name | missings |     Values |   N
#> ---+--------------+----------+------------+----
#> 1  | Sepal.Length | 0 (0.0%) | [4.3, 7.9] | 150
#> ---+--------------+----------+------------+----
#> 2  |  Sepal.Width | 0 (0.0%) |   [2, 4.4] | 150
#> ---+--------------+----------+------------+----
#> 3  | Petal.Length | 0 (0.0%) |   [1, 6.9] | 150
#> ---+--------------+----------+------------+----
#> 4  |  Petal.Width | 0 (0.0%) | [0.1, 2.5] | 150
#> ---+--------------+----------+------------+----
#> 5  |      Species | 0 (0.0%) |     setosa |  50
#>    |              |          | versicolor |  50
#>    |              |          |  virginica |  50
#> -----------------------------------------------

data(iris)
iris$Sepal.Width <- NA
data_codebook(iris)
#> Warning: Following 1 columns were empty and have been removed:
#>   Sepal.Width
#> iris (total N=150)
#> 
#> ID |         Name | missings |     Values |   N
#> ---+--------------+----------+------------+----
#> 1  | Sepal.Length | 0 (0.0%) | [4.3, 7.9] | 150
#> ---+--------------+----------+------------+----
#> 2  | Petal.Length | 0 (0.0%) |   [1, 6.9] | 150
#> ---+--------------+----------+------------+----
#> 3  |  Petal.Width | 0 (0.0%) | [0.1, 2.5] | 150
#> ---+--------------+----------+------------+----
#> 4  |      Species | 0 (0.0%) |     setosa |  50
#>    |              |          | versicolor |  50
#>    |              |          |  virginica |  50
#> -----------------------------------------------

data(efc)
data_codebook(efc)
#> efc (total N=100)
#> 
#> ID |     Name |  missings |                                    Label |   Values |                    Value Labels |  N
#> ---+----------+-----------+------------------------------------------+----------+---------------------------------+---
#> 1  |  c12hour |  2 (0.0%) | average number of hours of care per week | [5, 168] |                                 | 98
#> ---+----------+-----------+------------------------------------------+----------+---------------------------------+---
#> 2  |   e16sex |  0 (0.0%) |                           elder's gender |        1 |                            male | 46
#>    |          |           |                                          |        2 |                          female | 54
#> ---+----------+-----------+------------------------------------------+----------+---------------------------------+---
#> 3  |   e42dep |  3 (0.0%) |                       elder's dependency |        1 |                     independent |  2
#>    |          |           |                                          |        2 |              slightly dependent |  4
#>    |          |           |                                          |        3 |            moderately dependent | 28
#>    |          |           |                                          |        4 |              severely dependent | 63
#> ---+----------+-----------+------------------------------------------+----------+---------------------------------+---
#> 4  | c172code | 10 (0.1%) |               carer's level of education |        1 |          low level of education |  8
#>    |          |           |                                          |        2 | intermediate level of education | 66
#>    |          |           |                                          |        3 |         high level of education | 16
#> ---+----------+-----------+------------------------------------------+----------+---------------------------------+---
#> 5  |  neg_c_7 |  3 (0.0%) |             Negative impact with 7 items |  [7, 28] |                                 | 97
#> ----------------------------------------------------------------------------------------------------------------------

data_codebook(efc, label_width = 30)
#> efc (total N=100)
#> 
#> ID |     Name |  missings |                        Label |   Values |                    Value Labels |  N
#> ---+----------+-----------+------------------------------+----------+---------------------------------+---
#> 1  |  c12hour |  2 (0.0%) |   average number of hours of | [5, 168] |                                 | 98
#>    |          |           |                care per week |          |                                 |   
#> ---+----------+-----------+------------------------------+----------+---------------------------------+---
#> 2  |   e16sex |  0 (0.0%) |               elder's gender |        1 |                            male | 46
#>    |          |           |                              |        2 |                          female | 54
#> ---+----------+-----------+------------------------------+----------+---------------------------------+---
#> 3  |   e42dep |  3 (0.0%) |           elder's dependency |        1 |                     independent |  2
#>    |          |           |                              |        2 |              slightly dependent |  4
#>    |          |           |                              |        3 |            moderately dependent | 28
#>    |          |           |                              |        4 |              severely dependent | 63
#> ---+----------+-----------+------------------------------+----------+---------------------------------+---
#> 4  | c172code | 10 (0.1%) |   carer's level of education |        1 |          low level of education |  8
#>    |          |           |                              |        2 | intermediate level of education | 66
#>    |          |           |                              |        3 |         high level of education | 16
#> ---+----------+-----------+------------------------------+----------+---------------------------------+---
#> 5  |  neg_c_7 |  3 (0.0%) | Negative impact with 7 items |  [7, 28] |                                 | 97
#> ----------------------------------------------------------------------------------------------------------

x <- data_codebook(efc)
print_md(x)
```

| ID  |     Name |  missings | Label                                    | Values     |                    Value Labels | N   |
|:----|---------:|----------:|:-----------------------------------------|:-----------|--------------------------------:|:----|
| 1   |  c12hour |  2 (0.0%) | average number of hours of care per week | \[5, 168\] |                                 | 98  |
|     |          |           |                                          |            |                                 |     |
| 2   |   e16sex |  0 (0.0%) | elder’s gender                           | 1          |                            male | 46  |
|     |          |           |                                          | 2          |                          female | 54  |
|     |          |           |                                          |            |                                 |     |
| 3   |   e42dep |  3 (0.0%) | elder’s dependency                       | 1          |                     independent | 2   |
|     |          |           |                                          | 2          |              slightly dependent | 4   |
|     |          |           |                                          | 3          |            moderately dependent | 28  |
|     |          |           |                                          | 4          |              severely dependent | 63  |
|     |          |           |                                          |            |                                 |     |
| 4   | c172code | 10 (0.1%) | carer’s level of education               | 1          |          low level of education | 8   |
|     |          |           |                                          | 2          | intermediate level of education | 66  |
|     |          |           |                                          | 3          |         high level of education | 16  |
|     |          |           |                                          |            |                                 |     |
| 5   | neg_c\_7 |  3 (0.0%) | Negative impact with 7 items             | \[7, 28\]  |                                 | 97  |
|     |          |           |                                          |            |                                 |     |

efc (total N=100)

<sup>Created on 2022-11-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by etiennebacher** [comment]
I think it would be more convenient to have the variable label just next to the variable name

**Comment by IndrajeetPatil** [comment]
Takes one weekend off, comes back to find 4 new functions in the package 👀

**Comment by etiennebacher** [comment]
"He's not here to enforce best practices! Quick, make 4 PRs!"

**Pull request merged**
