### PR TITLE
implement fuzzy grep to detect misspelled columns

### PR DESCRIPTION
**Pull request by strengejacke**
``` r
library(datawizard)
out <- data.frame(
  Parameter = "Test",
  Median = 0.5,
  CI_low = 0.4,
  CI_high = 0.6,
  pd = .97,
  Rhat = .99,
  ESS = 1000,
  log_BF = 3
)

# close match
data_relocate(out, "pd", before = "BF")
#> Error: The column passed to `before` wasn't found. Did you mean "log_BF"?

# close multiple matches
data_relocate(out, "pd", before = "CIl")
#> Error: The column passed to `before` wasn't found. Did you mean one of "CI_low"
#>   or "CI_high"?

# not even close
data_relocate(out, "pd", before = "xyz")
#> Error: The column passed to `before` wasn't found. Possibly mispelled?

data(iris)

head(center(iris, "Sepla.Length"))
#> Warning: Following variable(s) were not found: Sepla.Length
#>    Did you mean one of "Sepal.Length" or "Petal.Length"?
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1          5.1         3.5          1.4         0.2  setosa
#> 2          4.9         3.0          1.4         0.2  setosa
#> 3          4.7         3.2          1.3         0.2  setosa
#> 4          4.6         3.1          1.5         0.2  setosa
#> 5          5.0         3.6          1.4         0.2  setosa
#> 6          5.4         3.9          1.7         0.4  setosa

head(standardise(iris, c("Sepla.Length", "Specia")))
#> Warning: Following variable(s) were not found: Sepla.Length, Specia
#>    Did you mean one of "Sepal.Length", "Petal.Length" or "Species"?
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1          5.1         3.5          1.4         0.2  setosa
#> 2          4.9         3.0          1.4         0.2  setosa
#> 3          4.7         3.2          1.3         0.2  setosa
#> 4          4.6         3.1          1.5         0.2  setosa
#> 5          5.0         3.6          1.4         0.2  setosa
#> 6          5.4         3.9          1.7         0.4  setosa
```

<sup>Created on 2022-10-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by strengejacke** [comment]
@IndrajeetPatil @etiennebacher WDTY? (see examples in initial post)

**Comment by strengejacke** [comment]
```r
library(datawizard)
data(iris)

# close match
data_relocate(iris, "Sepal.Length", before = "Specia")
#> Error: The column passed to `before` wasn't found.
#>   Did you mean "Species"?

# close multiple matches
data_relocate(iris, "Species", before = "Sepla.Length")
#> Error: The column passed to `before` wasn't found.
#>   Did you mean one of "Sepal.Length" or "Petal.Length"?

# not even close
data_relocate(iris, "Species", before = "xyz")
#> Error: The column passed to `before` wasn't found.
#>   Possibly misspelled?

# again, no perfect match
head(center(iris, select = "Sepla.Length"), 2)
#> Warning: Following variable(s) were not found: Sepla.Length
#>   Did you mean one of "Sepal.Length" or "Petal.Length"?
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1          5.1         3.5          1.4         0.2  setosa
#> 2          4.9         3.0          1.4         0.2  setosa

# both selected were misspelled
head(standardise(iris, select = c("Sepla.Length", "Specia")), 2)
#> Warning: Following variable(s) were not found: Sepla.Length, Specia
#>   Did you mean one of "Sepal.Length", "Petal.Length" or "Species"?
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1          5.1         3.5          1.4         0.2  setosa
#> 2          4.9         3.0          1.4         0.2  setosa

# unqouted variable names misspelled
data_select(iris, select = Sepal.Length:Specia)
#> Error: Could not find variable "Specia" in data.
#>   Did you mean "Species"?
```

**Review by IndrajeetPatil — APPROVED** [review]
As usual, really cool stuff, @strengejacke!

**Comment by strengejacke** [comment]
And more than 5 possible matches works, too:

``` r
data(efc, package = "sjmisc")
colnames(efc)
#>  [1] "c12hour"  "e15relat" "e16sex"   "e17age"   "e42dep"   "c82cop1" 
#>  [7] "c83cop2"  "c84cop3"  "c85cop4"  "c86cop5"  "c87cop6"  "c88cop7" 
#> [13] "c89cop8"  "c90cop9"  "c160age"  "c161sex"  "c172code" "c175empl"
#> [19] "barthtot" "neg_c_7"  "pos_v_4"  "quol_5"   "resttotn" "tot_sc_e"
#> [25] "n4pstu"   "nur_pst"
datawizard::center(efc, "c82cop") |> head(2)
#> Warning: Following variable(s) were not found: c82cop
#>   Did you mean one of "c82cop1", "c83cop2", "c84cop3", "c85cop4" or
#>   "c86cop5"? We even found 4 more possible matches, not shown here.
#>   c12hour e15relat e16sex e17age e42dep c82cop1 c83cop2 c84cop3 c85cop4 c86cop5
#> 1      16        2      2     83      3       3       2       2       2       1
#> 2     148        2      2     88      3       3       3       3       3       4
#>   c87cop6 c88cop7 c89cop8 c90cop9 c160age c161sex c172code c175empl barthtot
#> 1       1       2       3       3      56       2        2        1       75
#> 2       1       3       2       2      54       2        2        1       75
#>   neg_c_7 pos_v_4 quol_5 resttotn tot_sc_e n4pstu nur_pst
#> 1      12      12     14        0        4      0      NA
#> 2      20      11     10        4        0      0      NA
```

<sup>Created on 2022-10-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by etiennebacher** [comment]
I wasn't available this weekend, but this looks very cool!

**Pull request merged**
