### PR TITLE
Fix `.select_nse()`

### LINKED ISSUE #377: {parameters} failures with dev-version of {datawizazard}
I get following failures when I check _parameters_ with the dev-version of _datawizard_:

https://github.com/easystats/parameters/actions/runs/4423924240/jobs/7757144347

https://github.com/easystats/parameters/actions/runs/4423924245/jobs/7757144195

### PR DESCRIPTION
**Pull request by etiennebacher**
Close #377

Fixes related failed tests in parameters locally

### CODE REVIEW

**Comment by etiennebacher** [comment]
I see a bunch of action failures, I can't work on this now but can you test parameters locally with this branch?

**Comment by strengejacke** [comment]
First seems to be fixed. Second one not. Seems to be in `datawizard::visualisation_recipe()`.

``` r
library(parameters)
library(see)

set.seed(33) # Set random seed

data <- iris[1:4]
rez_kmeans <- cluster_analysis(data, n = 3, method = "kmeans")

s <- summary(rez_kmeans)
s
#>   Cluster Sepal.Length Sepal.Width Petal.Length Petal.Width
#> 1       1   -1.3232208  -0.3718921   -1.1334386  -1.1111395
#> 2       2   -0.8135055   1.3145538   -1.2825372  -1.2156393
#> 3       3    0.5690971  -0.3705265    0.6888118   0.6609378

class(s)
#> [1] "cluster_analysis_summary" "data.frame"

plot(s)
#> Error: No columns found for reshaping data.
# calls: plot(datawizard::visualisation_recipe(x, ...))
```

<sup>Created on 2023-03-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
Some infos from the backtrace

```
! No columns found for reshaping data.
Backtrace:
 1. base::plot(summary(rez_kmeans))
 2. parameters:::plot.cluster_analysis_summary(summary(rez_kmeans))
 5. parameters:::visualisation_recipe.cluster_analysis_summary(...)
      at datawizard/R/visualisation_recipe.R:23:2
 6. datawizard::data_to_long(...)
    ...
      at datawizard/R/data_to_long.R:121:4
 8. insight::format_alert(..., type = "error")
      at insight/R/format_message.R:1[55](https://github.com/easystats/parameters/actions/runs/4424837477/jobs/7759139217#step:7:56):2
 9. base::stop(...)
      at insight/R/format_message.R:137:4
  |.................
```

**Comment by etiennebacher** [comment]
Should be fixed now
``` r
library(see)
library(parameters)

set.seed(33)
data <- iris[, 1:4]
rez_kmeans <- cluster_analysis(data, n = 3, method = "kmeans")
s <- summary(rez_kmeans)
s
#>   Cluster Sepal.Length Sepal.Width Petal.Length Petal.Width
#> 1       1   -1.3232208  -0.3718921   -1.1334386  -1.1111395
#> 2       2   -0.8135055   1.3145538   -1.2825372  -1.2156393
#> 3       3    0.5690971  -0.3705265    0.6888118   0.6609378
class(s)
#> [1] "cluster_analysis_summary" "data.frame"
plot(s)
```

**Review by strengejacke — APPROVED** [review]

**Pull request merged**
