### PR TITLE
[Feature] categorize() gets `label="mean/median"` option 

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Review by IndrajeetPatil — CHANGES_REQUESTED** [review]
Thanks. Prima facie, looks good.

Can you please add unit tests to check the correct behaviour?

**Comment by strengejacke** [comment]
Need a unit test for

```r
set.seed(123)
x <- sample(c(1:10, NA), size = 30, replace = TRUE)
categorize(x, "equal_length", n_groups = 3, labels = "mean")
categorize(x, "equal_length", n_groups = 3, labels = "median")
```

**Comment by strengejacke** [comment]
_bump_

**Comment by strengejacke** [comment]
_bump_

**Review by strengejacke — APPROVED** [review]

**Pull request merged**
