### PR TITLE
Fix snapshot tests

### LINKED ISSUE #559: Fix snapshot tests
The new default (on github) of `insight::export_table(width = "auto")` is breaking the snapshot tests.

### PR DESCRIPTION
**Pull request by strengejacke**
Fixes #559

### CODE REVIEW

**Comment by strengejacke** [comment]
@mattansb @etiennebacher What do you think, should we have a `table_width` argument in the `print()` method for `data_codebook()`, too, which is set to `NULL` / `Inf` (to make previous behaviour the default)? Or should `"auto"` be the default? In the special case of `data_codebook()`, empty lines in split tables are filled with dashes (see snapshot-test md-files in this PR).

```
Code
  print(data_codebook(efc), table_width = Inf)
Output
  efc (100 rows and 5 variables, 5 shown)
  
  ID | Name     | Label                                    | Type        |   Missings |   Values | Value Labels                    |          N
  ---+----------+------------------------------------------+-------------+------------+----------+---------------------------------+-----------
  1  | c12hour  | average number of hours of care per week | numeric     |   2 (2.0%) | [5, 168] |                                 |         98
  ---+----------+------------------------------------------+-------------+------------+----------+---------------------------------+-----------
  2  | e16sex   | elder's gender                           | numeric     |   0 (0.0%) |        1 | male                            | 46 (46.0%)
     |          |                                          |             |            |        2 | female                          | 54 (54.0%)
  ---+----------+------------------------------------------+-------------+------------+----------+---------------------------------+-----------
  3  | e42dep   | elder's dependency                       | categorical |   3 (3.0%) |        1 | independent                     |  2 ( 2.1%)
     |          |                                          |             |            |        2 | slightly dependent              |  4 ( 4.1%)
     |          |                                          |             |            |        3 | moderately dependent            | 28 (28.9%)
     |          |                                          |             |            |        4 | severely dependent              | 63 (64.9%)
  ---+----------+------------------------------------------+-------------+------------+----------+---------------------------------+-----------
  4  | c172code | carer's level of education               | numeric     | 10 (10.0%) |        1 | low level of education          |  8 ( 8.9%)
     |          |                                          |             |            |        2 | intermediate level of education | 66 (73.3%)
     |          |                                          |             |            |        3 | high level of education         | 16 (17.8%)
  ---+----------+------------------------------------------+-------------+------------+----------+---------------------------------+-----------
  5  | neg_c_7  | Negative impact with 7 items             | numeric     |   3 (3.0%) |  [7, 28] |                                 |         97
  ---------------------------------------------------------------------------------------------------------------------------------------------
```

versus

```
Code
  print(data_codebook(efc), table_width = "auto")
Output
  efc (100 rows and 5 variables, 5 shown)
  
  ID | Name     | Label                                    | Type       
  ---+----------+------------------------------------------+------------
  1  | c12hour  | average number of hours of care per week | numeric    
  ---+----------+------------------------------------------+------------
  2  | e16sex   | elder's gender                           | numeric    
  ---+----------+------------------------------------------+------------
  ---+----------+------------------------------------------+------------
  3  | e42dep   | elder's dependency                       | categorical
  ---+----------+------------------------------------------+------------
  ---+----------+------------------------------------------+------------
  ---+----------+------------------------------------------+------------
  ---+----------+------------------------------------------+------------
  4  | c172code | carer's level of education               | numeric    
  ---+----------+------------------------------------------+------------
  ---+----------+------------------------------------------+------------
  ---+----------+------------------------------------------+------------
  5  | neg_c_7  | Negative impact with 7 items             | numeric    
  ----------------------------------------------------------------------
  
  ID |   Missings |   Values | Value Labels                    |          N
  ---+------------+----------+---------------------------------+-----------
  1  |   2 (2.0%) | [5, 168] |                                 |         98
  ---+------------+----------+---------------------------------+-----------
  2  |   0 (0.0%) |        1 | male                            | 46 (46.0%)
     |            |        2 | female                          | 54 (54.0%)
  ---+------------+----------+---------------------------------+-----------
  3  |   3 (3.0%) |        1 | independent                     |  2 ( 2.1%)
     |            |        2 | slightly dependent              |  4 ( 4.1%)
     |            |        3 | moderately dependent            | 28 (28.9%)
     |            |        4 | severely dependent              | 63 (64.9%)
  ---+------------+----------+---------------------------------+-----------
  4  | 10 (10.0%) |        1 | low level of education          |  8 ( 8.9%)
     |            |        2 | intermediate level of education | 66 (73.3%)
     |            |        3 | high level of education         | 16 (17.8%)
  ---+------------+----------+---------------------------------+-----------
  5  |   3 (3.0%) |  [7, 28] |                                 |         97
  -------------------------------------------------------------------------
```

**Comment by mattansb** [comment]
I think we should keep the "auto" default.

But the behavior of empty rows looks off. 

Current behavior:

```R
options(width = 80)
print(datawizard::data_codebook(ggeffects::efc[,1:2]))
#> 
#> ID | Name     | Label                                    | Type    | Missings
#> ---+----------+------------------------------------------+---------+---------
#> 1  | c12hour  | average number of hours of care per week | numeric | 6 (0.7%)
#> ---+----------+------------------------------------------+---------+---------
#> 2  | e15relat | relationship to elder                    | numeric | 7 (0.8%)
#> ---+----------+------------------------------------------+---------+---------
#> ---+----------+------------------------------------------+---------+---------
#> ---+----------+------------------------------------------+---------+---------
#> ---+----------+------------------------------------------+---------+---------
#> ---+----------+------------------------------------------+---------+---------
#> ---+----------+------------------------------------------+---------+---------
#> ---+----------+------------------------------------------+---------+---------
#> -----------------------------------------------------------------------------
#> 
#> ID |   Values | Value Labels            |           N
#> ---+----------+-------------------------+------------
#> 1  | [4, 168] |                         |         902
#> ---+----------+-------------------------+------------
#> 2  |        1 | spouse/partner          | 171 (19.0%)
#>    |        2 | child                   | 473 (52.5%)
#>    |        3 | sibling                 |  29 ( 3.2%)
#>    |        4 | daughter or son -in-law |  85 ( 9.4%)
#>    |        5 | ancle/aunt              |  23 ( 2.6%)
#>    |        6 | nephew/niece            |  22 ( 2.4%)
#>    |        7 | cousin                  |   6 ( 0.7%)
#>    |        8 | other, specify          |  92 (10.2%)
#> -----------------------------------------------------
```

But I would prefer empty cells to be empty (not ---) separated by | (not +):

```R
print(datawizard::data_codebook(ggeffects::efc[,1:2]))
#> 
#> ID | Name     | Label                                    | Type    | Missings
#> ---+----------+------------------------------------------+---------+---------
#> 1  | c12hour  | average number of hours of care per week | numeric | 6 (0.7%)
#> ---+----------+------------------------------------------+---------+---------
#> 2  | e15relat | relationship to elder                    | numeric | 7 (0.8%)
#>    |          |                                          |         |
#>    |          |                                          |         |
#>    |          |                                          |         |
#>    |          |                                          |         |
#>    |          |                                          |         |
#>    |          |                                          |         |
#>    |          |                                          |         |
#> -----------------------------------------------------------------------------
#> 
#> ID |   Values | Value Labels            |           N
#> ---+----------+-------------------------+------------
#> 1  | [4, 168] |                         |         902
#> ---+----------+-------------------------+------------
#> 2  |        1 | spouse/partner          | 171 (19.0%)
#>    |        2 | child                   | 473 (52.5%)
#>    |        3 | sibling                 |  29 ( 3.2%)
#>    |        4 | daughter or son -in-law |  85 ( 9.4%)
#>    |        5 | ancle/aunt              |  23 ( 2.6%)
#>    |        6 | nephew/niece            |  22 ( 2.4%)
#>    |        7 | cousin                  |   6 ( 0.7%)
#>    |        8 | other, specify          |  92 (10.2%)
#> -----------------------------------------------------
```

Even better would be to skip such lines (though maybe that's confusing?):

```R
print(datawizard::data_codebook(ggeffects::efc[,1:2]))
#> 
#> ID | Name     | Label                                    | Type    | Missings
#> ---+----------+------------------------------------------+---------+---------
#> 1  | c12hour  | average number of hours of care per week | numeric | 6 (0.7%)
#> ---+----------+------------------------------------------+---------+---------
#> 2  | e15relat | relationship to elder                    | numeric | 7 (0.8%)
#> -----------------------------------------------------------------------------
#> 
#> ID |   Values | Value Labels            |           N
#> ---+----------+-------------------------+------------
#> 1  | [4, 168] |                         |         902
#> ---+----------+-------------------------+------------
#> 2  |        1 | spouse/partner          | 171 (19.0%)
#>    |        2 | child                   | 473 (52.5%)
#>    |        3 | sibling                 |  29 ( 3.2%)
#>    |        4 | daughter or son -in-law |  85 ( 9.4%)
#>    |        5 | ancle/aunt              |  23 ( 2.6%)
#>    |        6 | nephew/niece            |  22 ( 2.4%)
#>    |        7 | cousin                  |   6 ( 0.7%)
#>    |        8 | other, specify          |  92 (10.2%)
#> -----------------------------------------------------
```

**Comment by strengejacke** [comment]
See https://github.com/easystats/insight/pull/953

Doesn't work perfect if the last row in the data frame is a duplicate - then, there are two table lines at the bottom, this still needs to be fixed:

``` r
print(datawizard::data_codebook(ggeffects::efc[, 1:4]), remove_duplicates = FALSE)
#> ggeffects::efc[, 1:4] (908 rows and 4 variables, 4 shown)
#> 
#> ID | Name     | Label                                    | Type    |  Missings
#> ---+----------+------------------------------------------+---------+----------
#> 1  | c12hour  | average number of hours of care per week | numeric |  6 (0.7%)
#> ---+----------+------------------------------------------+---------+----------
#> 2  | e15relat | relationship to elder                    | numeric |  7 (0.8%)
#>    |          |                                          |         |          
#>    |          |                                          |         |          
#>    |          |                                          |         |          
#>    |          |                                          |         |          
#>    |          |                                          |         |          
#>    |          |                                          |         |          
#>    |          |                                          |         |          
#> ---+----------+------------------------------------------+---------+----------
#> 3  | e16sex   | elder's gender                           | numeric |  7 (0.8%)
#>    |          |                                          |         |          
#> ---+----------+------------------------------------------+---------+----------
#> 4  | e17age   | elder' age                               | numeric | 17 (1.9%)
#> ------------------------------------------------------------------------------
#> 
#> ID |    Values | Value Labels            |           N
#> ---+-----------+-------------------------+------------
#> 1  |  [4, 168] |                         |         902
#> ---+-----------+-------------------------+------------
#> 2  |         1 | spouse/partner          | 171 (19.0%)
#>    |         2 | child                   | 473 (52.5%)
#>    |         3 | sibling                 |  29 ( 3.2%)
#>    |         4 | daughter or son -in-law |  85 ( 9.4%)
#>    |         5 | ancle/aunt              |  23 ( 2.6%)
#>    |         6 | nephew/niece            |  22 ( 2.4%)
#>    |         7 | cousin                  |   6 ( 0.7%)
#>    |         8 | other, specify          |  92 (10.2%)
#> ---+-----------+-------------------------+------------
#> 3  |         1 | male                    | 296 (32.9%)
#>    |         2 | female                  | 605 (67.1%)
#> ---+-----------+-------------------------+------------
#> 4  | [65, 103] |                         |         891
#> ------------------------------------------------------
print(datawizard::data_codebook(ggeffects::efc[, 1:4]), remove_duplicates = TRUE)
#> ggeffects::efc[, 1:4] (908 rows and 4 variables, 4 shown)
#> 
#> ID | Name     | Label                                    | Type    |  Missings
#> ---+----------+------------------------------------------+---------+----------
#> 1  | c12hour  | average number of hours of care per week | numeric |  6 (0.7%)
#> ---+----------+------------------------------------------+---------+----------
#> 2  | e15relat | relationship to elder                    | numeric |  7 (0.8%)
#> ---+----------+------------------------------------------+---------+----------
#> 3  | e16sex   | elder's gender                           | numeric |  7 (0.8%)
#> ---+----------+------------------------------------------+---------+----------
#> 4  | e17age   | elder' age                               | numeric | 17 (1.9%)
#> ------------------------------------------------------------------------------
#> 
#> ID |    Values | Value Labels            |           N
#> ---+-----------+-------------------------+------------
#> 1  |  [4, 168] |                         |         902
#> ---+-----------+-------------------------+------------
#> 2  |         1 | spouse/partner          | 171 (19.0%)
#>    |         2 | child                   | 473 (52.5%)
#>    |         3 | sibling                 |  29 ( 3.2%)
#>    |         4 | daughter or son -in-law |  85 ( 9.4%)
#>    |         5 | ancle/aunt              |  23 ( 2.6%)
#>    |         6 | nephew/niece            |  22 ( 2.4%)
#>    |         7 | cousin                  |   6 ( 0.7%)
#>    |         8 | other, specify          |  92 (10.2%)
#> ---+-----------+-------------------------+------------
#> 3  |         1 | male                    | 296 (32.9%)
#>    |         2 | female                  | 605 (67.1%)
#> ---+-----------+-------------------------+------------
#> 4  | [65, 103] |                         |         891
#> ------------------------------------------------------

print(datawizard::data_codebook(ggeffects::efc[, 1:3]), remove_duplicates = FALSE)
#> ggeffects::efc[, 1:3] (908 rows and 3 variables, 3 shown)
#> 
#> ID | Name     | Label                                    | Type    | Missings
#> ---+----------+------------------------------------------+---------+---------
#> 1  | c12hour  | average number of hours of care per week | numeric | 6 (0.7%)
#> ---+----------+------------------------------------------+---------+---------
#> 2  | e15relat | relationship to elder                    | numeric | 7 (0.8%)
#>    |          |                                          |         |         
#>    |          |                                          |         |         
#>    |          |                                          |         |         
#>    |          |                                          |         |         
#>    |          |                                          |         |         
#>    |          |                                          |         |         
#>    |          |                                          |         |         
#> ---+----------+------------------------------------------+---------+---------
#> 3  | e16sex   | elder's gender                           | numeric | 7 (0.8%)
#> ---+----------+------------------------------------------+---------+---------
#> -----------------------------------------------------------------------------
#> 
#> ID |   Values | Value Labels            |           N
#> ---+----------+-------------------------+------------
#> 1  | [4, 168] |                         |         902
#> ---+----------+-------------------------+------------
#> 2  |        1 | spouse/partner          | 171 (19.0%)
#>    |        2 | child                   | 473 (52.5%)
#>    |        3 | sibling                 |  29 ( 3.2%)
#>    |        4 | daughter or son -in-law |  85 ( 9.4%)
#>    |        5 | ancle/aunt              |  23 ( 2.6%)
#>    |        6 | nephew/niece            |  22 ( 2.4%)
#>    |        7 | cousin                  |   6 ( 0.7%)
#>    |        8 | other, specify          |  92 (10.2%)
#> ---+----------+-------------------------+------------
#> 3  |        1 | male                    | 296 (32.9%)
#>    |        2 | female                  | 605 (67.1%)
#> -----------------------------------------------------
print(datawizard::data_codebook(ggeffects::efc[, 1:3]), remove_duplicates = TRUE)
#> ggeffects::efc[, 1:3] (908 rows and 3 variables, 3 shown)
#> 
#> ID | Name     | Label                                    | Type    | Missings
#> ---+----------+------------------------------------------+---------+---------
#> 1  | c12hour  | average number of hours of care per week | numeric | 6 (0.7%)
#> ---+----------+------------------------------------------+---------+---------
#> 2  | e15relat | relationship to elder                    | numeric | 7 (0.8%)
#> ---+----------+------------------------------------------+---------+---------
#> 3  | e16sex   | elder's gender                           | numeric | 7 (0.8%)
#> ---+----------+------------------------------------------+---------+---------
#> -----------------------------------------------------------------------------
#> 
#> ID |   Values | Value Labels            |           N
#> ---+----------+-------------------------+------------
#> 1  | [4, 168] |                         |         902
#> ---+----------+-------------------------+------------
#> 2  |        1 | spouse/partner          | 171 (19.0%)
#>    |        2 | child                   | 473 (52.5%)
#>    |        3 | sibling                 |  29 ( 3.2%)
#>    |        4 | daughter or son -in-law |  85 ( 9.4%)
#>    |        5 | ancle/aunt              |  23 ( 2.6%)
#>    |        6 | nephew/niece            |  22 ( 2.4%)
#>    |        7 | cousin                  |   6 ( 0.7%)
#>    |        8 | other, specify          |  92 (10.2%)
#> ---+----------+-------------------------+------------
#> 3  |        1 | male                    | 296 (32.9%)
#>    |        2 | female                  | 605 (67.1%)
#> -----------------------------------------------------
```

<sup>Created on 2024-11-03 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by mattansb** [comment]
Why is this only an issue for the last row? 🤔

**Comment by strengejacke** [comment]
I'm looking for _consecutive duplicated lines_, and these will be removed (from first duplicated to the one before the lase - we want to keep one line that separates data rows).

In the 2nd example with three columns, we have following for the last data row (e16sex):

```
 ---+----------+------------------------------------------+---------+---------
 ---+----------+------------------------------------------+---------+---------
 -----------------------------------------------------------------------------
```` 

one of the two duplicated lines is removed, the other one is preserved as separator for the next data row - but there's no next data row, there's only the last line (which is not a duplicate, because it has no `+` signs).

**Comment by strengejacke** [comment]
I think we have to fix this somewhere in the new code that removes the duplicates:

https://github.com/easystats/insight/pull/953/files#diff-cafb3e0523369ec1d779f9377d74656f6e10b4a9131008d3f87a4e2c8a5482e1R734-R777

**Comment by strengejacke** [comment]
ok, should be fixed. Once the PR in insight is merged, we can run checks here again

**Comment by etiennebacher** [comment]
I'm confused about those changes. Does the default print method for `data_codebook()` produces a different output? If so, I don't know whether this change is necessary but it should be mentioned in the news as a breaking change (and the required version of `insight` should be bumped?).

**Comment by mattansb** [comment]
This is an easystats-wide change to make outputs more console-friendly.

The insight req versions should be bumped, yes.

**Comment by strengejacke** [comment]
What do you mean by different output?

**Comment by strengejacke** [comment]
Basically, the `table_width` argument in `insight::export_table()` now defaults to `"auto"`, and it can now split tables into as many parts as required to make the table-width fit into the console (previously, a maximum of two splits were possible).

The major issue is `table_width = "auto"` now. While previously wide tables were overflowing and printed in the next console line (and the table looked a bit messy), now tables are more readable. This doesn't work for this reprex of course, but the screenshots below show it quite well:

``` r
print(datawizard::data_codebook(ggeffects::efc[, 1:3]), table_width = Inf)
#> ggeffects::efc[, 1:3] (908 rows and 3 variables, 3 shown)
#> 
#> ID | Name     | Label                                    | Type    | Missings |   Values | Value Labels            |           N
#> ---+----------+------------------------------------------+---------+----------+----------+-------------------------+------------
#> 1  | c12hour  | average number of hours of care per week | numeric | 6 (0.7%) | [4, 168] |                         |         902
#> ---+----------+------------------------------------------+---------+----------+----------+-------------------------+------------
#> 2  | e15relat | relationship to elder                    | numeric | 7 (0.8%) |        1 | spouse/partner          | 171 (19.0%)
#>    |          |                                          |         |          |        2 | child                   | 473 (52.5%)
#>    |          |                                          |         |          |        3 | sibling                 |  29 ( 3.2%)
#>    |          |                                          |         |          |        4 | daughter or son -in-law |  85 ( 9.4%)
#>    |          |                                          |         |          |        5 | ancle/aunt              |  23 ( 2.6%)
#>    |          |                                          |         |          |        6 | nephew/niece            |  22 ( 2.4%)
#>    |          |                                          |         |          |        7 | cousin                  |   6 ( 0.7%)
#>    |          |                                          |         |          |        8 | other, specify          |  92 (10.2%)
#> ---+----------+------------------------------------------+---------+----------+----------+-------------------------+------------
#> 3  | e16sex   | elder's gender                           | numeric | 7 (0.8%) |        1 | male                    | 296 (32.9%)
#>    |          |                                          |         |          |        2 | female                  | 605 (67.1%)
#> --------------------------------------------------------------------------------------------------------------------------------

print(datawizard::data_codebook(ggeffects::efc[, 1:3]))
#> ggeffects::efc[, 1:3] (908 rows and 3 variables, 3 shown)
#> 
#> ID | Name     | Label                                    | Type    | Missings
#> ---+----------+------------------------------------------+---------+---------
#> 1  | c12hour  | average number of hours of care per week | numeric | 6 (0.7%)
#> ---+----------+------------------------------------------+---------+---------
#> 2  | e15relat | relationship to elder                    | numeric | 7 (0.8%)
#>    |          |                                          |         |         
#>    |          |                                          |         |         
#>    |          |                                          |         |         
#>    |          |                                          |         |         
#>    |          |                                          |         |         
#>    |          |                                          |         |         
#>    |          |                                          |         |         
#> ---+----------+------------------------------------------+---------+---------
#> 3  | e16sex   | elder's gender                           | numeric | 7 (0.8%)
#>    |          |                                          |         |         
#> -----------------------------------------------------------------------------
#> 
#> ID |   Values | Value Labels            |           N
#> ---+----------+-------------------------+------------
#> 1  | [4, 168] |                         |         902
#> ---+----------+-------------------------+------------
#> 2  |        1 | spouse/partner          | 171 (19.0%)
#>    |        2 | child                   | 473 (52.5%)
#>    |        3 | sibling                 |  29 ( 3.2%)
#>    |        4 | daughter or son -in-law |  85 ( 9.4%)
#>    |        5 | ancle/aunt              |  23 ( 2.6%)
#>    |        6 | nephew/niece            |  22 ( 2.4%)
#>    |        7 | cousin                  |   6 ( 0.7%)
#>    |        8 | other, specify          |  92 (10.2%)
#> ---+----------+-------------------------+------------
#> 3  |        1 | male                    | 296 (32.9%)
#>    |        2 | female                  | 605 (67.1%)
#> -----------------------------------------------------
```

<sup>Created on 2024-11-04 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

image

image

**Comment by etiennebacher** [comment]
Ok, that sounds good to me. I was wondering whether this would also change the output when the console is wide enough to support the full table without splitting, but apparently this is not the case. I don't believe anyone relies on the current overflowing behavior and the main change comes from `insight`, so I don't think we need to put this in news here.

**Review by etiennebacher — APPROVED** [review]

**Comment by etiennebacher** [comment]
@strengejacke I'm not sure the conversation with @mattansb is resolved so I'll let you merge if it is.

**Comment by strengejacke** [comment]
> Ok, thanks for the explanation, this sounds good to me. I was wondering whether this would also change the output when the console is wide enough to support the full table without splitting, but apparently this is not the case. I don't believe anyone relies on the current overflowing behavior and the main change comes from `insight`, so I don't think we need to put this in news here.

If the table width ("output") fits into the console (i.e. console is wide enough), no new behaviour occurs. It's literally only an improvement. And even in vignettes, e.g. here:
https://easystats.github.io/parameters/articles/model_parameters.html
the table is not split, because the markdown document sets the line width to 120:
```
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 120))
```
only tables *wider* than 120 chars would be split into several chunks.

**Pull request merged**
