### PR TITLE
export `distribution_mode()`

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by strengejacke** [comment]
Do we want to have a new function, or to integrate this in `describe_distribution.factor()`?

**Comment by strengejacke** [comment]
Ah, got it. This was meant as addition to `mean` etc. Why not `mode`?

**Comment by strengejacke** [comment]
What should `distribution_mode(iris$Species)` return? just one, or all three levels? @mattansb @bwiernik ?

**Comment by strengejacke** [comment]
``` r
library(datawizard)
distribution_mode(iris$Species)
#> [1] setosa
#> Levels: setosa versicolor virginica

uniqv <- unique(iris$Species)
tab <- tabulate(match(iris$Species, uniqv))
idx <- which(tab == max(tab))
uniqv[idx]
#> [1] setosa     versicolor virginica 
#> Levels: setosa versicolor virginica
```

<sup>Created on 2022-05-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bwiernik** [comment]
All three levels I think

**Comment by IndrajeetPatil** [comment]
If there is a tie, the first element should be returned, right?

E.g., currently, ` distribution_mode(c(1, 2, 3, 3, 4, 4, 5))` returns `3` and not `c(3, 4)`, and the same holds for factors as well?

**Comment by bwiernik** [comment]
Do we export the function for MAP? Might be goods to link to it with seeAlso and say that it may be better for continuous variables

**Comment by bwiernik** [comment]
@IndrajeetPatil Yes, but I interpreted Daniel's questions about being about the factor levels. We shouldn't re-level the factor but instead preserve the original levels. 

Should we have a warning or message when there are multiple modes?

**Comment by strengejacke** [comment]
Yeah, I was actually meaning how we should deal with ties, i.e. just the first, or more values. For MAP, we have `bayestestR::map_estimate()` or `bayestestR::point_estimate(centrality = "MAP")`.

**Comment by bwiernik** [comment]
I think maybe the first and give a message/warning about multiple modes. Maybe with an attribute with all of them? Or maybe we make a new value like 'Setosa, Versicolor' and save the individual values as an attribute

**Comment by strengejacke** [comment]
Showing first, give a warning and all as attribute sounds good.

**Review by strengejacke — APPROVED** [review]

**Comment by elinw** [comment]
> Showing first, give a warning and all as attribute sounds good.

Was this  implemented?

**Comment by strengejacke** [comment]
Yes: https://easystats.github.io/datawizard/reference/distribution_mode.html

**Comment by strengejacke** [comment]
Ah, you mean the warning? No, not yet implemented.

**Pull request merged**
