### PR TITLE
Do not load packages with `library()` in tests

### PR DESCRIPTION
**Pull request by etiennebacher**
https://github.com/easystats/easystats/issues/363

~~DO NOT MERGE: wait for 0.7.1 to be on CRAN (submitted, waiting for answer)~~

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
@etiennebacher Btw, we no longer have the styler workflow, so you need to manually run styler and push changes 🥲

**Review by IndrajeetPatil — COMMENTED** [review]
Why are the two snapshots files deleted? I am guessing that was accidental?

**Comment by etiennebacher** [comment]
Hum probably, but I'll review and clean the PR once 0.7.1 is on CRAN

**Comment by IndrajeetPatil** [comment]
@etiennebacher Can you please not skip CI?

We already cancel workflows in progress if a new commit appears. But if the last commit skips CI then there is no way to tell if everything is in order because CI for the entire PR is now absent.

**Comment by etiennebacher** [comment]
You can go in the tab "Checks" and then select the latest commit that has CI

**Comment by IndrajeetPatil** [comment]
Another problem is that if this PR is merged into main, CI won't run and website won't be built. 

Ideally, the website is always in sync with the default branch.

**Comment by etiennebacher** [comment]
ah, right

**Comment by strengejacke** [comment]
> True, but the GitHub mobile app doesn't let me access this feature.

Tick "desktop version" in Chrome and you can then look at checks via browser on your mobile phone.

**Comment by IndrajeetPatil** [comment]
> > True, but the GitHub mobile app doesn't let me access this feature.
> 
> 
> 
> Tick "desktop version" in Chrome and you can then look at checks via browser on your mobile phone.

Cool. Thanks for the tip!

**Comment by strengejacke** [comment]
(here's a link if you don't find desktop-mode immediately: https://www.browserstack.com/guide/view-desktop-sites-on-android)

**Review by IndrajeetPatil — APPROVED** [review]
Tests are finally passing in the random order!!

Thanks a lot for working painstakingly and patiently on disentangling this mess 👏

**Comment by etiennebacher** [comment]
image

**Pull request merged**
