### PR TITLE
Update DESCRIPTION

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
Testing workflows

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
This Matrix update is the bane of my existence.

**Comment by IndrajeetPatil** [comment]
giphy

**Comment by etiennebacher** [comment]
Thanks a lot Indra!

**Comment by IndrajeetPatil** [comment]
de rien!

But I am not sure if it still works. I had to make a lot of changes again to make sure things also work for _performance_, and not just _datawizard_.

**Pull request merged**
