### PR TITLE
Remove super assign

### PR DESCRIPTION
**Pull request by etiennebacher**
https://github.com/easystats/easystats/issues/358

### CODE REVIEW

**Comment by etiennebacher** [comment]
There are test failures that are extremely weird because they are caused by loading *parameters* in another test file but inside a test_that call. I'll put some details later

**Comment by etiennebacher** [comment]
And there are some CRAN failures to fix btw

**Comment by IndrajeetPatil** [comment]
Yeah, we are going to need to put work in a few repos to follow the best practices for isolating unit tests.

**Comment by IndrajeetPatil** [comment]
Yeah, we are going to need to put work in a few repos to follow the best practices for isolating unit tests.

**Comment by IndrajeetPatil** [comment]
How did our CI/CD not catch this?! 😞

**Comment by strengejacke** [comment]
> And there are some CRAN failures to fix btw

All mac issues... It's on the arm64 architecture, maybe x86 works? I would probably skip those tests on mac os x, or increase tolerance.

**Comment by IndrajeetPatil** [comment]
Hmm, tests still don't pass when run in a random order 🤔

**Comment by IndrajeetPatil** [comment]
We can get to it later. Merging for now.

**Pull request merged**
