### PR TITLE
Remove some aliases

### LINKED ISSUE #265: Getting rid of aliases for selection functions
Screenshot 2022-09-14 at 20 50 05

- `get_columns()` is confusing because, unless you read the docs, it is not clear whether the function returns column names, or a list of vectors, or a data frame. `data_select()` is much better, since we have established that `data_*()` functions always return a data frame. Keeping the `get_columns()` around for long is inviting confusion.

- The same is true for `data_find()`. All other `data_*()` functions return data frames, while this one returns an atomic vector. This messes user's mental model. We should remove it in favour of `find_columns()`.

``` r
library(datawizard)
data_find(iris, starts_with("Sepal"))
#> [1] "Sepal.Length" "Sepal.Width"
```

<sup>Created on 2022-09-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This is probably something we can do in `0.7` or later.

### PR DESCRIPTION
**Pull request by etiennebacher**
Close #265

### CODE REVIEW

**Comment by etiennebacher** [comment]
Test failures same as https://github.com/easystats/datawizard/pull/502#issuecomment-2118998595

**Review by strengejacke — APPROVED** [review]

**Comment by IndrajeetPatil** [comment]
Looks like we have some encoding issues for Windows prior to `R 4.2` that need fixing?

```r
== Failed tests ================================================================
-- Failure ('test-data_read.R:348:5'): data_read, convert many labels correctly --
attributes(d$selv1)$labels (`actual`) not identical to c(...) (`expected`).

names(actual) vs names(expected)
- "Vignette 1 weiblich (Gülsen E. Reinigungskraft B)"
+ "Vignette 1 weiblich (GÃ¼lsen E. Reinigungskraft B)"
- "Vignette 2 weiblich (Gülsen E. Anwältin B)"
+ "Vignette 2 weiblich (GÃ¼lsen E. AnwÃ¤ltin B)"
  "Vignette 3 weiblich (Monika E. Reinigungskraft B)"
- "Vignette 4 weiblich (Monika E. Anwältin B)"
+ "Vignette 4 weiblich (Monika E. AnwÃ¤ltin B)"
- "Vignette 5 männlich (Hasan E. Reinigungskraft B)"
+ "Vignette 5 mÃ¤nnlich (Hasan E. Reinigungskraft B)"
- "Vignette 6 männlich (Hasan E. Anwalt B)"
+ "Vignette 6 mÃ¤nnlich (Hasan E. Anwalt B)"
- "Vignette 7 männlich (Martin E. Reinigungskraft B)"
+ "Vignette 7 mÃ¤nnlich (Martin E. Reinigungskraft B)"
- "Vignette 8 männlich (Martin E. Anwalt B)"
+ "Vignette 8 mÃ¤nnlich (Martin E. Anwalt B)"
- "Vignette 9 weiblich (Gülsen E. Reinigungskraft E)"
+ "Vignette 9 weiblich (GÃ¼lsen E. Reinigungskraft E)"
- "Vignette 10 weiblich (Gülsen E. Anwältin E)"
+ "Vignette 10 weiblich (GÃ¼lsen E. AnwÃ¤ltin E)"
  "Vignette 11 weiblich (Monika E. Reinigungskraft E)"
- "Vignette 12 weiblich (Monika E. Anwältin E)"
+ "Vignette 12 weiblich (Monika E. AnwÃ¤ltin E)"
- "Vignette 13 männlich (Hasan E. Reinigungskraft E)"
+ "Vignette 13 mÃ¤nnlich (Hasan E. Reinigungskraft E)"
- "Vignette 14 männlich (Hasan E. Anwalt E)"
+ "Vignette 14 mÃ¤nnlich (Hasan E. Anwalt E)"
- "Vignette 15 männlich (Martin E. Reinigungskraft E)"
+ "Vignette 15 mÃ¤nnlich (Martin E. Reinigungskraft E)"
- "Vignette 16 männlich (Martin E. Anwalt E)"
+ "Vignette 16 mÃ¤nnlich (Martin E. Anwalt E)"
  "99"
Backtrace:
    x
 1. \-withr::with_tempfile(...) at test-data_read.R:275:3
 2.   \-base::eval(substitute(code), envir = env)
 3.     \-base::eval(substitute(code), envir = env)
 4.       \-testthat::expect_identical(...) at test-data_read.R:348:5
-- Failure ('test-data_read.R:378:5'): data_read, convert many labels correctly --
attributes(d$c12c)$labels (`actual`) not identical to c(...) (`expected`).

     names(actual)               | names(expected)                  
[10] "8"                         | "8"                          [10]
[11] "9"                         | "9"                          [11]
[12] "10 = sehr starke"          | "10 = sehr starke"           [12]
[13] "weiß nicht / keine Angabe" - "weiÃŸ nicht / keine Angabe" [13]
Backtrace:
    x
 1. \-withr::with_tempfile(...) at test-data_read.R:275:3
 2.   \-base::eval(substitute(code), envir = env)
 3.     \-base::eval(substitute(code), envir = env)
 4.       \-testthat::expect_identical(...) at test-data_read.R:378:5

[ FAIL 2 | WARN 0 | SKIP 3 | PASS [201](https://github.com/easystats/datawizard/actions/runs/9145947600/job/25145489411?pr=504#step:7:203)4 ]
Error: Error: Test failures
Execution halted

Error: Error: R CMD check found ERRORs
Execution halted
1 error x | 0 warnings v | 1 note x
```

**Comment by etiennebacher** [comment]
I'll take a look but we only use reading functions from other packages so maybe the error originates in one of them. If so I'll report it to them

**Comment by IndrajeetPatil** [comment]
Sounds good.

And thanks for cleaning the lints! 🧹

**Review by IndrajeetPatil — APPROVED** [review]

**Comment by strengejacke** [comment]
> Looks like we have some encoding issues for Windows prior to `R 4.2` that need fixing?

This one is new and shouldn't be related to any changes from us / in our packages.

**Comment by strengejacke** [comment]
@IndrajeetPatil Do we need the favicons for all our packages now?

**Comment by IndrajeetPatil** [comment]
@strengejacke No, this is just a bandaid. The issue should be fixed soon upstream in pkgdown. I am switching to CRAN version of pkgdown until this is resolved.

**Comment by etiennebacher** [comment]
> Looks like we have some encoding issues for Windows prior to `R 4.2` that need fixing?

I'm very confused about this. I can reproduce on Windows with R 4.1.3 when I run the `testthat` functions or buttons in RStudio, but running all the code by hand works fine:

image

Also, we use `haven` to read this type of data but it hasn't been updated in 6 months so it's probably not it. Checking if this could come from `testthat` / `waldo`

**Comment by strengejacke** [comment]
I also can't find any relevant changes to `data_read()` the past months / year.

**Comment by etiennebacher** [comment]
Only thing I can think of is a change in the CI because of changes in `r-lib/actions` but I can't find anything related: https://github.com/r-lib/actions/blob/v2-branch/NEWS.md

**Comment by etiennebacher** [comment]
Actually we started testing on Windows with R 4.1 very recently: https://github.com/easystats/workflows/commit/54e04870f8aadcaa75d7aa8f077d0fba3481f081

This might have been broken for a while

**Comment by strengejacke** [comment]
We added that test over a year ago (https://github.com/easystats/datawizard/commit/fe74c965935954341d574c48a3b9db89885a5fe3#diff-6529e485b0d7b1e2df1af2fc885a3dbbb0fcec8eacaff61963679ffd7df001d6), it should have occurred on the "old-R" tests back than.

**Pull request merged**
