### PR TITLE
Check with insight get data PR

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
@strengejacke Creating a new PR to test _datawizard_'s behaviour with the _insight_ PR.

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Following tests fail:

```r
══ Failed tests ════════════════════════════════════════════════════════════════
── Failure ('test-data_to_numeric.R:29'): convert character to numeric lowest ──
to_numeric(insight::get_response(model), dummy_factors = FALSE) (`actual`) not equal to c(...) (`expected`).

  `actual`: 0 0 1 1 0 1 0 1 1 1 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0 1 0 0 0 1
`expected`: 1 1 2 2 1 2 1 2 2 2 2 1 1 1 1 1 1 2 2 2 2 1 1 1 1 2 1 2 1 1 1 2
── Error ('test-standardize_models.R:139'): weights + NA ───────────────────────
Error in `eval(extras, data, env)`: object 'weight_me' not found
Backtrace:
     ▆
  1. ├─datawizard::standardize(m1, weights = FALSE) at test-standardize_models.R:139:2
  2. └─datawizard:::standardize.default(m1, weights = FALSE) at datawizard/R/standardize.R:122:2
  3.   └─datawizard:::.standardize_models(...) at datawizard/R/standardize.models.R:82:2
  4.     ├─base::eval(substitute(update_expr)) at datawizard/R/standardize.models.R:264:4
  5.     │ └─base::eval(substitute(update_expr))
  6.     ├─stats::update(x, data = data_std)
  7.     ├─stats::update.default(x, data = data_std)
  8.     │ └─base::eval(call, parent.frame())
  9.     │   └─base::eval(call, parent.frame())
 10.     ├─stats::lm(...)
 11.     │ └─base::eval(mf, parent.frame())
 12.     │   └─base::eval(mf, parent.frame())
 13.     ├─stats::model.frame(...)
 14.     └─stats::model.frame.default(...)
 15.       └─base::eval(extras, data, env)
 16.         └─base::eval(extras, data, env)
── Error ('test-standardize_models.R:139'): weights + NA ───────────────────────
Error: Error: Unable to refit the model with standardized data.
  Try instead to standardize the data (standardize(data)) and refit the
  model manually.
Backtrace:
    ▆
 1. ├─datawizard::standardize(m1, weights = FALSE) at test-standardize_models.R:139:2
 2. └─datawizard:::standardize.default(m1, weights = FALSE) at datawizard/R/standardize.R:122:2
 3.   └─datawizard:::.standardize_models(...) at datawizard/R/standardize.models.R:82:2
 4.     └─datawizard:::.update_failed() at datawizard/R/standardize.models.R:82:2
 5.       └─insight::format_error(msg1, "Try instead to standardize the data (standardize(data)) and refit the model manually.") at datawizard/R/standardize.models.R:520:2
 6.         └─insight::format_alert(..., type = "error") at insight/R/format_message.R:151:2
── Error ('test-standardize_models.R:179'): fail with subset ───────────────────
Error in `lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...)`: 0 (non-NA) cases
Backtrace:
     ▆
  1. ├─testthat::expect_error(standardise(mod1), regexp = "subset") at test-standardize_models.R:179:2
  2. │ └─testthat:::expect_condition_matching(...)
  3. │   └─testthat:::quasi_capture(...)
  4. │     ├─testthat (local) .capture(...)
  5. │     │ └─base::withCallingHandlers(...)
  6. │     └─rlang::eval_bare(quo_get_expr(.quo), quo_get_env(.quo))
  7. ├─datawizard::standardise(mod1)
  8. └─datawizard:::standardize.default(mod1) at datawizard/R/standardize.R:122:2
  9.   └─datawizard:::.standardize_models(...) at datawizard/R/standardize.models.R:82:2
 10.     ├─base::eval(substitute(update_expr)) at datawizard/R/standardize.models.R:264:4
 11.     │ └─base::eval(substitute(update_expr))
 12.     ├─stats::update(x, data = data_std)
 13.     ├─stats::update.default(x, data = data_std)
 14.     │ └─base::eval(call, parent.frame())
 15.     │   └─base::eval(call, parent.frame())
 16.     └─stats::lm(...)
 17.       └─stats::lm.fit(...)
── Error ('test-standardize_models.R:179'): fail with subset ───────────────────
Error: Error: Unable to refit the model with standardized data.
  Try instead to standardize the data (standardize(data)) and refit the
  model manually.
Backtrace:
     ▆
  1. ├─testthat::expect_error(standardise(mod1), regexp = "subset") at test-standardize_models.R:179:2
  2. │ └─testthat:::expect_condition_matching(...)
  3. │   └─testthat:::quasi_capture(...)
  4. │     ├─testthat (local) .capture(...)
  5. │     │ └─base::withCallingHandlers(...)
  6. │     └─rlang::eval_bare(quo_get_expr(.quo), quo_get_env(.quo))
  7. ├─datawizard::standardise(mod1)
  8. └─datawizard:::standardize.default(mod1) at datawizard/R/standardize.R:122:2
  9.   └─datawizard:::.standardize_models(...) at datawizard/R/standardize.models.R:82:2
 10.     └─datawizard:::.update_failed() at datawizard/R/standardize.models.R:82:2
 11.       └─insight::format_error(msg1, "Try instead to standardize the data (standardize(data)) and refit the model manually.") at datawizard/R/standardize.models.R:520:2
 12.         └─insight::format_alert(..., type = "error") at insight/R/format_message.R:151:2
── Failure ('test-standardize_models.R:204'): variables evaluated in the environment ──
any(grepl("mtcars$mpg", w, fixed = TRUE)) is not TRUE

`actual`:   FALSE
`expected`: TRUE 
── Failure ('test-standardize_models.R:212'): variables evaluated in the environment ──
any(grepl("mtcars$mpg", warns, fixed = TRUE)) is not TRUE

`actual`:   FALSE
`expected`: TRUE 
── Failure ('test-standardize_models.R:213'): variables evaluated in the environment ──
any(grepl("No variables", warns, fixed = TRUE)) is not TRUE

`actual`:   FALSE
`expected`: TRUE 

[ FAIL 8 | WARN 8 | SKIP 104 | PASS 1034 ]
```

**Comment by mattansb** [comment]
Please don't merge this before I have a chance to see that this is behaving properly!

**Comment by strengejacke** [comment]
Don't worry, I guess it will require some careful reviews before we merge the PRs

**Comment by strengejacke** [comment]
Should work both with the insight-PR and insight-main.

**Pull request merged**
