### PR TITLE
`data_arrange`: return data early if already sorted

### PR DESCRIPTION
**Pull request by etiennebacher**
No need to waste time if data is already sorted. This can save some time on large datasets but only works when there's only one variable used to arrange the data

### CODE REVIEW

**Review by IndrajeetPatil — APPROVED** [review]
LGTM, thanks!

**Comment by strengejacke** [comment]
``` r
.is_sorted <- Negate(is.unsorted)
select <- c("Sepal.Length", "Petal.Width", "Sepal.Width")
d <- iris[order(iris$Petal.Width), ]

microbenchmark::microbenchmark(
  all(unlist(lapply(d[, select, drop = FALSE], .is_sorted))),
  all(vapply(d[, select, drop = FALSE], .is_sorted, logical(1))),
  times = 1000
)
#> Unit: microseconds
#>                                                            expr  min   lq
#>      all(unlist(lapply(d[, select, drop = FALSE], .is_sorted))) 22.1 22.7
#>  all(vapply(d[, select, drop = FALSE], .is_sorted, logical(1))) 21.8 22.3
#>     mean median    uq    max neval cld
#>  25.2288   23.0 23.65 1455.2  1000   a
#>  23.2329   22.6 23.20   76.4  1000   a
```

<sup>Created on 2022-10-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
The min time is close, but the max time is larger fo lapply.

**Comment by etiennebacher** [comment]
I have very large changes each time I run this. I even got something 40x slower for `vapply`. I think `is.unsorted` is fast enough

**Comment by etiennebacher** [comment]
``` r
.is_sorted <- Negate(is.unsorted)
select <- c("Sepal.Length", "Petal.Width", "Sepal.Width")
d <- iris[order(iris$Petal.Width), ]

x <- bench::mark(
  lapply = all(unlist(lapply(d[, select, drop = FALSE], .is_sorted))),
  vapply = all(vapply(d[, select, drop = FALSE], .is_sorted, logical(1))),
  iterations = 10000
)

ggplot2::autoplot(x)
#> Loading required namespace: tidyr
```



<sup>Created on 2022-10-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
yeah, strange. You may revert `vapply` back to `lapply` if you want. I guess it depends on the algorithm of `is.unsorted` how long this check is

**Comment by etiennebacher** [comment]
> yeah, strange. You may revert vapply back to lapply if you want

it's ok, it didn't change code readability. I just thought that we needed to get rid of `sapply`, not `lapply`

> Can you redo the benchmark with a larger data frame? 

On a dataset with 340k rows:

``` r
.is_sorted <- Negate(is.unsorted)
select <- c("dep_time", "tailnum", "flight")
d <- nycflights13::flights[order(nycflights13::flights$tailnum), ]

x <- bench::mark(
  lapply = all(unlist(lapply(d[, select, drop = FALSE], .is_sorted))),
  vapply = all(vapply(d[, select, drop = FALSE], .is_sorted, logical(1))),
  iterations = 10000
)

ggplot2::autoplot(x)
#> Loading required namespace: tidyr
```



<sup>Created on 2022-10-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Pull request merged**
