### PR TITLE
Put vignettes in `.Rbuildignore`

### LINKED ISSUE #527: Fix build failures on macOS 4.3
cf. https://cloud.r-project.org/web/checks/check_results_datawizard.html

```r
Version: 0.12.1
Check: running R code from vignettes
Result: ERROR 
  Errors in running code in vignettes:
  when running code in ‘tidyverse_translation.Rmd’
    ...
  > if (!all(vapply(pkgs, requireNamespace, quietly = TRUE, 
  +     FUN.VALUE = logical(1))) || getRversion() < "4.1.0") {
  +     evaluate_chunk <- FALSE
   .... [TRUNCATED] 
  
  > row("Note: In this vignette, we use the native pipe-operator, `|>`, which was introduced in R 4.1. Users of R version 3.6 or 4.0 should replace the  ..." ... [TRUNCATED] 
  
    When sourcing ‘tidyverse_translation.R’:
  Error: a matrix-like object is required as argument to 'row'
  Execution halted
  
    ‘selection_syntax.Rmd’ using ‘UTF-8’... [1s/1s] OK
    ‘standardize_data.Rmd’ using ‘UTF-8’... [4s/5s] OK
    ‘tidyverse_translation.Rmd’ using ‘UTF-8’... failed
Flavor: [r-oldrel-macos-arm64](https://www.r-project.org/nosvn/R.check/r-oldrel-macos-arm64/datawizard-00check.html)
```

As discussed elsewhere, a solution might just be to rename the `row()` function to not collide with `base::row()`.

### PR DESCRIPTION
**Pull request by etiennebacher**
Close #527

### CODE REVIEW

**Review by strengejacke — APPROVED** [review]

**Comment by etiennebacher** [comment]
@strengejacke is it fine if I make a new release now to fix those errors on macOS?

**Comment by strengejacke** [comment]
Yes. We could also merge #533 before, wdyt?

**Comment by etiennebacher** [comment]
It seems the discussion in #530 is not finished and I'd like jmgirard to review the PR if possible, I don't think I can say anything meaningful on the implementation in itself

**Comment by strengejacke** [comment]
His feedback was "This looks correct". :-)
But let's bump a reminder....

**Comment by strengejacke** [comment]
> @strengejacke is it fine if I make a new release now to fix those errors on macOS?

I think you can plan your release w/o waiting for #535, that PR's not urgent.

**Comment by etiennebacher** [comment]
Ok I'll make the release

**Pull request merged**
