### PR TITLE
tibble-issue

### LINKED ISSUE #404: tibble-issue
Once again, tibbles do not behave like data frames despite pretending to be one. This leads to warnings in `data_join()`, although there's no issue.

``` r
library(datawizard)
iris <- tibble::as_tibble(iris)
is.null(iris$.test)
#> Warning: Unknown or uninitialised column: `.test`.
#> [1] TRUE
".test" %in% colnames(iris)
#> [1] FALSE

data_join(iris, iris[20:30, ], join = "bind")
#> Warning: Unknown or uninitialised column: `.data_merge_row`.
#> Warning: Unknown or uninitialised column: `.data_merge_id_x`.
#> # A tibble: 161 × 5
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>           <dbl>       <dbl>        <dbl>       <dbl> <fct>  
#>  1          5.1         3.5          1.4         0.2 setosa 
#>  2          4.9         3            1.4         0.2 setosa 
#>  3          4.7         3.2          1.3         0.2 setosa 
#>  4          4.6         3.1          1.5         0.2 setosa 
#>  5          5           3.6          1.4         0.2 setosa 
#>  6          5.4         3.9          1.7         0.4 setosa 
#>  7          4.6         3.4          1.4         0.3 setosa 
#>  8          5           3.4          1.5         0.2 setosa 
#>  9          4.4         2.9          1.4         0.2 setosa 
#> 10          4.9         3.1          1.5         0.1 setosa 
#> # ℹ 151 more rows

data_join(iris, data_filter(iris, 20:30), join = "bind")
#> Warning: Unknown or uninitialised column: `.data_merge_row`.
#> Unknown or uninitialised column: `.data_merge_id_x`.
#> # A tibble: 161 × 5
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>           <dbl>       <dbl>        <dbl>       <dbl> <fct>  
#>  1          5.1         3.5          1.4         0.2 setosa 
#>  2          4.9         3            1.4         0.2 setosa 
#>  3          4.7         3.2          1.3         0.2 setosa 
#>  4          4.6         3.1          1.5         0.2 setosa 
#>  5          5           3.6          1.4         0.2 setosa 
#>  6          5.4         3.9          1.7         0.4 setosa 
#>  7          4.6         3.4          1.4         0.3 setosa 
#>  8          5           3.4          1.5         0.2 setosa 
#>  9          4.4         2.9          1.4         0.2 setosa 
#> 10          4.9         3.1          1.5         0.1 setosa 
#> # ℹ 151 more rows
```

<sup>Created on 2023-04-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I suggest replacing `!is.null(data$var)`  with `"var" %in% colnames(data)`.

### PR DESCRIPTION
**Pull request by strengejacke**
Fixes #404

### CODE REVIEW

**Comment by strengejacke** [comment]
@etiennebacher For tests, we need the tibble package and would need to add this to "suggests". Not sure if you prefer additional tests here?

**Comment by strengejacke** [comment]
I looked at the other occurences of `is.null(data$var)`, I think these are not affected by the tibble-class.

**Comment by IndrajeetPatil** [comment]
I think it's fine to add tibble to  Suggests because dplyr already downloads it, so we are not gaining an additional soft dependency. It will be good to have a regression test here.

**Review by IndrajeetPatil — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
